var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,b,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");e!=Array.prototype&&e!=Object.prototype&&(e[b]=f.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.iterator;e||(e=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[e]&&$jscomp.defineProperty(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(e){var b=0;return $jscomp.iteratorPrototype(function(){return b<e.length?{done:!1,value:e[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(e){$jscomp.initSymbolIterator();e={next:e};e[$jscomp.global.Symbol.iterator]=function(){return this};return e};$jscomp.polyfill=function(e,b,f,d){if(b){f=$jscomp.global;e=e.split(".");for(d=0;d<e.length-1;d++){var c=e[d];c in f||(f[c]={});f=f[c]}e=e[e.length-1];d=f[e];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(f,e,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.from",function(e){return e?e:function(b,e,d){$jscomp.initSymbolIterator();e=null!=e?e:function(a){return a};var c=[],a=b[Symbol.iterator];if("function"==typeof a)for(b=a.call(b);!(a=b.next()).done;)c.push(e.call(d,a.value));else for(var a=b.length,f=0;f<a;f++)c.push(e.call(d,b[f]));return c}},"es6-impl","es3");$jscomp.makeIterator=function(e){$jscomp.initSymbolIterator();var b=e[Symbol.iterator];return b?b.call(e):$jscomp.arrayIterator(e)};
$jscomp.owns=function(e,b){return Object.prototype.hasOwnProperty.call(e,b)};
$jscomp.polyfill("WeakMap",function(e){function b(a){$jscomp.owns(a,d)||$jscomp.defineProperty(a,d,{value:{}})}function f(a){var d=Object[a];d&&(Object[a]=function(a){b(a);return d(a)})}if(function(){if(!e||!Object.seal)return!1;try{var a=Object.seal({}),d=Object.seal({}),c=new e([[a,2],[d,3]]);if(2!=c.get(a)||3!=c.get(d))return!1;c["delete"](a);c.set(d,4);return!c.has(a)&&4==c.get(d)}catch(m){return!1}}())return e;var d="$jscomp_hidden_"+Math.random().toString().substring(2);f("freeze");f("preventExtensions");
f("seal");var c=0,a=function(a){this.id_=(c+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};a.prototype.set=function(a,c){b(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=c;return this};a.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};a.prototype.has=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};a.prototype["delete"]=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return a},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(e){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!e||!e.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),d=new e($jscomp.makeIterator([[a,"s"]]));if("s"!=d.get(a)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),b=c.next();if(b.done||b.value[0]!=a||"s"!=b.value[1])return!1;b=c.next();return b.done||4!=b.value[0].x||"t"!=b.value[1]||!c.next().done?!1:!0}catch(n){return!1}}())return e;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var b=new WeakMap,f=function(d){this.data_={};this.head_=a();this.size=0;if(d){d=$jscomp.makeIterator(d);for(var c;!(c=d.next()).done;)c=c.value,this.set(c[0],c[1])}};f.prototype.set=function(a,c){var b=d(this,a);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=c:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:c},b.list.push(b.entry),this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};f.prototype["delete"]=
function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=a();this.size=0};f.prototype.has=function(a){return!!d(this,a).entry};f.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};f.prototype.entries=function(){return c(this,function(a){return[a.key,
a.value]})};f.prototype.keys=function(){return c(this,function(a){return a.key})};f.prototype.values=function(){return c(this,function(a){return a.value})};f.prototype.forEach=function(a,d){for(var c=this.entries(),b;!(b=c.next()).done;)b=b.value,a.call(d,b[1],b[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var d=function(a,d){var c;c=d&&typeof d;"object"==c||"function"==c?b.has(d)?c=b.get(d):(c=""+ ++h,b.set(d,c)):c="p_"+d;var e=a.data_[c];if(e&&$jscomp.owns(a.data_,c))for(var f=0;f<
e.length;f++){var p=e[f];if(d!==d&&p.key!==p.key||d===p.key)return{id:c,list:e,index:f,entry:p}}return{id:c,list:e,index:-1,entry:void 0}},c=function(a,d){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:d(c)};c=null}return{done:!0,value:void 0}})},a=function(){var a={};return a.previous=a.next=a.head=a},h=0;return f},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(e){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!e||!e.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new e($jscomp.makeIterator([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var c=d.entries(),a=c.next();if(a.done||a.value[0]!=b||a.value[1]!=b)return!1;a=c.next();return a.done||a.value[0]==b||4!=a.value[0].x||a.value[1]!=a.value[0]?!1:c.next().done}catch(h){return!1}}())return e;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=function(b){this.map_=new Map;if(b){b=$jscomp.makeIterator(b);for(var d;!(d=b.next()).done;)this.add(d.value)}this.size=this.map_.size};b.prototype.add=function(b){this.map_.set(b,b);this.size=this.map_.size;return this};b.prototype["delete"]=function(b){b=this.map_["delete"](b);this.size=this.map_.size;return b};b.prototype.clear=function(){this.map_.clear();this.size=0};b.prototype.has=function(b){return this.map_.has(b)};b.prototype.entries=
function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(b,d){var c=this;this.map_.forEach(function(a){return b.call(d,a,a,c)})};return b},"es6-impl","es3");$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(e,b){$jscomp.initSymbolIterator();e instanceof String&&(e+="");var f=0,d={next:function(){if(f<e.length){var c=f++;return{value:b(c,e[c]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(e){return e?e:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6-impl","es3");
var AboutPage=function(){return{initialize:function(e){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){window.location=App.getPiecePath()})},draw:function(){},getPath:function(){return"about.html"}}}(),AJAX=function(){return{GET:function(e,b,f){b=void 0===b?null:b;f=void 0===f?null:f;var d=new XMLHttpRequest;d.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==b&&b(this.responseText):null!==f&&f(this.status))};
d.open("GET",e,!0);d.send()}}}(),CatalogPage=function(){function e(){AJAX.GET(App.getPiecesPath()+"indexes.json",function(b){b=JSON.parse(b);var e=b.scales;1==a.length?b.hasOwnProperty(a[0])&&(e=b[a[0]]):1<a.length&&"scales"==a[0]&&b.scales.hasOwnProperty(a[1])&&(e=b.scales[a[1]]);c={query:a,tiles:[]};b=[];for(g in e)e.hasOwnProperty(g)&&"_"!==g.substring(0,1)&&b.push(g);b.sort(function(a,b){var c=Locale.getTranslation(e[a]._desc,"en"),d=Locale.getTranslation(e[b]._desc,"en");return c<d?-1:c>d?1:
0});for(var f=0;f<b.length;f++){var g=b[f],n=e[g];if("_"!==g.substring(0,1)){var g={id:g,description:n._desc},p=0;for(keyInNextLevel in n)n.hasOwnProperty(keyInNextLevel)&&"_"!==keyInNextLevel.substring(0,1)&&(p+=1);0>=p?g.type="piece":(g.type="folder",g.total=p);c.tiles.push(g)}}d()})}function b(a){a=a.target.getAttribute("data");window.location=App.getPagePath(CatalogPage)+"?q="+encodeURIComponent("scales,"+a)}function f(a){window.location=App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a.target.getAttribute("data"))}
function d(){for(var a=0;a<c.tiles.length;a++){var d=c.tiles[a];if("folder"==d.type){var e=document.createElement("div");e.classList.add("tile");e.classList.add("folder");e.setAttribute("data",d.id);e.innerHTML=Locale.getTranslation(d.description);e.addEventListener("click",b);h.appendChild(e)}else e=document.createElement("div"),e.classList.add("tile"),e.classList.add("piece"),e.setAttribute("data",d.id),e.innerHTML=Locale.getTranslation(d.description),e.addEventListener("click",f),h.appendChild(e),
d.hasOwnProperty("data")}}var c={},a="",h=null;return{initialize:function(b){h=document.querySelector("div#tiles");window.hasOwnProperty("catalogSnapshot")&&(c=window.catalogSnapshot);parseInt(b.p);a=Array.from(new Set((b.q||"").split(",")));e()},draw:function(){},getPath:function(){return"catalog.html"}}}(),Header=function(){function e(){window.location=App.getPagePath(PDFPage)}function b(){window.location=App.getPagePath(SharePage)}function f(){window.location=App.getPagePath(CatalogPage)}function d(){window.location=
App.getPagePath(AboutPage)}var c=null,a=null,h=null;return{initialize:function(){c=document.querySelector("div#header > div#controls > div.control#pdf");c.addEventListener("click",e);a=document.querySelector("div#header > div#controls > div.control#share");a.addEventListener("click",b);h=document.querySelector("div#header > div#controls > div.control#open");h.addEventListener("click",f);document.querySelector("div#header > div#title  > div#text").addEventListener("click",d);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",
d);document.querySelector("div#header > div#title  > div#text").innerHTML=Locale.getApplicationTitle()},highlight:function(b){c.classList.remove("highlighted");a.classList.remove("highlighted");h.classList.remove("highlighted");b===PDFPage?c.classList.add("highlighted"):b===SharePage?a.classList.add("highlighted"):b===CatalogPage&&h.classList.add("highlighted")}}}(),IndexPage=function(){var e=null,b=0,f=function(){function d(a){a=a.target.id;e.getData();if("pre"===a){var d=e.getPreBar(b);a=e.getTotalVerticals()-
1;null!==d&&(a=d.first);window.location=window.location.pathname+"?p="+e.getData().id+"&v="+a}else"next"===a?(d=e.getNextBar(b),a=0,null!==d&&(a=d.first),window.location=window.location.pathname+"?p="+e.getData().id+"&v="+a):"reload"===a&&(window.location=window.location.pathname+"?p="+e.getData().id+"&v=0")}return{initialize:function(){for(var a=document.querySelectorAll("body > div#container > div#music > div#header > div#controls > div.control"),b=0;b<a.length;b++)a[b].addEventListener("click",
d)},enableControls:function(){for(var a=document.querySelectorAll("body > div#container > div#music > div#header > div#controls > div.control"),b=0;b<a.length;b++)a[b].classList.remove("disabled")}}}(),d=function(){function c(a){var b=a.clientX,d=a.clientY;"ontouchstart"in window&&(b=a.touches[0].clientX,d=a.touches[0].clientY);f(b,d)}function a(a){a=null;for(var c=document.querySelectorAll("body > div#container > div#notes > div.note"),f=0;f<c.length;f++)if(c[f].classList.contains("selected")){a=
c[f];break}if(null!==a){a.classList.remove("selected");StringInstrumentSimulator.stop();var c=e.getBar(b),f=b-c.first,g=c.verticals[f],g=Array.from(g.notes.keys());"playAllNotesAndMoveNext"!==a.id&&"muteAndMoveNext"!==a.id?(g=[parseInt(a.getAttribute("value"))],m.changeNotesColor(f,g,"green"),m.changeNotesSize(f,g,1)):(m.changeNotesColor(f,g,"black"),m.changeNotesSize(f,g,1),b+=1,a=!1,b>=c.first+c.verticals.length&&(a=!0),b>=e.getTotalVerticals()&&(b=0),a?d.firstDraw():(f+=1,g=c.verticals[f],g=Array.from(g.notes.keys()),
m.changeNotesColor(f,g,"green"),m.changeNotesSize(f,g,1),l()))}}function f(a,d){for(var c=null,f=document.querySelectorAll("body > div#container > div#notes > div.note"),g=0;g<f.length;g++){var n=f[g].getBoundingClientRect();if(a>=n.left&&a<=n.right&&d>=n.top&&d<=n.bottom){c=f[g];break}}if(null!==c){for(;!c.classList.contains("note");)c=c.parentNode;c.classList.add("selected");var g=e.getBar(b),f=b-g.first,n=g.verticals[f],h=[],k=[];if("playAllNotesAndMoveNext"===c.id)for(g=0;g<n.notes.length;g++)h.push(Note.getNoteFrequency(n.notes[g])),
k.push(g);else if("muteAndMoveNext"===c.id)for(g=0;g<n.notes.length;g++)h.push(0),k.push(g);else c=parseInt(c.getAttribute("value")),h.push(Note.getNoteFrequency(n.notes[c])),k.push(c);"r"===n.duration.substr(-1)?StringInstrumentSimulator.play([0]):StringInstrumentSimulator.play(h);m.changeNotesColor(f,k,"red");m.changeNotesSize(f,k,1.3)}}function l(){for(var a=document.querySelectorAll("body > div#container > div#notes > div.note"),c=0;c<a.length;c++)"playAllNotesAndMoveNext"!==a[c].id&&"muteAndMoveNext"!==
a[c].id&&a[c].parentNode.removeChild(a[c]);var a=document.querySelector("body > div#container > div#notes"),c=e.getBar(b),d=c.verticals[b-c.first];if("r"!==d.duration.substr(-1))for(c=d.notes.length-1;0<=c;c--){var f=document.createElement("div");f.classList.add("note");f.setAttribute("value",""+c);var h=f,k;k=Note.getNoteDetail(d.notes[c]);var l=""===k.accidental?"":"withAccidental";k=('<div class="natural YYY">'+k.natural+'</div><div class="accidental XXX"></div><div class="octave ZZZ">'+k.octave+
"</div>").replace("XXX",""===k.accidental?"hidden":k.accidental).replace("YYY",l).replace("ZZZ",l);h.innerHTML=k;a.appendChild(f)}}function k(){m.display();l()}var m=null;return{initialize:function(){var b="mousedown",d="mouseup";"ontouchstart"in window&&(b="touchstart",d="touchend");window.addEventListener(b,c);window.addEventListener(d,a);m=new MusicPlayer(document.querySelector("body > div#container > div#music > div#sheet"))},playNoteAtPosition:f,reDraw:k,firstDraw:function(){m.setPiece(e);m.setFocus(b);
k();var a=e.getBar(b),c=b-a.first;m.changeNotesColor(c,Array.from(a.verticals[c].notes.keys()),"green");document.querySelector("body > div#container > div#music > div#header > div#title").innerHTML=Locale.getTranslation(e.getData().descriptions)}}}();return{initialize:function(c){function a(a){b>=e.getTotalVerticals()&&(b=0);d.firstDraw();f.enableControls();null!==a&&d.playNoteAtPosition(a.x,a.y);sessionStorage.lastPieceId=e.getData().id;a=e.getNextBar(b);var c=0;null!==a&&(c=a.first);AJAX.GET(window.location.pathname+
"?p="+e.getData().id+"&v="+c)}var h=c.p||"default";b=parseInt(c.v)||0;var l=null;"unhandledEvent"in c&&c.lastPage===App.getPagePath(IndexPage)&&(l=c.unhandledEvent);d.initialize();f.initialize();e=MusicStorageManager.getPiece(h);null!==e?a(l):(LoadingIconManager.show(),AJAX.GET(App.getPiecesPath()+h+".json",function(c){e=Piece.createFromString(c);MusicStorageManager.setPiece(e);a(l);LoadingIconManager.hide()},function(a){alert(Locale.getPieceLoadingFailureNotice(h));window.location=App.getPagePath(CatalogPage)}))},
draw:function(){null!==e&&d.reDraw()},getPath:function(){return"index.html"}}}(),LoadingIconManager=function(){var e=0,b=document.querySelector("body > div#loading");return{show:function(){setTimeout(function(){110<(new Date).getTime()-e&&b.classList.remove("hidden")},100)},hide:function(){b.classList.add("hidden");e=(new Date).getTime()}}}(),Locale=function(){function e(){if("language"in localStorage&&0<=d.indexOf(localStorage.language))c=localStorage.language;else{var a=navigator.languages&&navigator.languages[0]||
navigator.language||navigator.userLanguage,a=a.toLowerCase();c=0<=d.indexOf(a)?a:"en"}}function b(a,b){var d;void 0===b&&(b=c);d=b in a?a[b]:a.en;for(var e=2;e<arguments.length;e++)d=d.replace("{"+(e-1)+"}",arguments[e]);return d}function f(a,c){if(null===a)return"";var b=a.getData().descriptions,d=b.en;b.hasOwnProperty(c)&&(d=b[c]);return d}var d=["en","zh-cn"],c="en",a={en:"HeliMusic","zh-cn":"\u55e8\u4e50"},h={en:"Violin","zh-cn":"\u5c0f\u63d0\u7434"},l={en:"More resources from {1}","zh-cn":"\u66f4\u591a\u8d44\u6e90\u5728 {1}"},
k={en:"Cannot load piece {1} from {2}. Please choose a new one.","zh-cn":"\u65e0\u6cd5\u4ece{2}\u4e0b\u8f7d\u66f2\u76ee{1}\u3002\u8bf7\u9009\u62e9\u65b0\u66f2\u76ee\u3002"},m={en:"Share <b>{1}</b> to your friends using buttons above or your browser's sharing functions!","zh-cn":"\u4f7f\u7528\u4e0a\u9762\u7684\u6309\u94ae\u6216\u8005\u6d4f\u89c8\u5668\u7684\u5206\u4eab\u529f\u80fd\u628a{1}\u5206\u4eab\u7ed9\u4f60\u7684\u670b\u53cb\uff01"};e();return{checkLanguage:e,getProjectName:function(c){return b(a,
c)},getApplicationTitle:function(a){return b(h,a)},getPrintFooter:function(a){return b(l,a,window.location.hostname)},getTranslation:b,getPieceLoadingFailureNotice:function(a,c){return b(k,c,a,App.getPiecesPath())},getSharingTitle:function(a,c){return b(m,c,f(a))},getPieceDescription:f}}();
function MusicPlayer(e){function b(a){for(var c=a.first,b=[],e=0;e<a.verticals.length;e++){for(var f=[],g=0;g<a.verticals[e].notes.length;g++)f.push({color:"black",size:"1.0"});b.push(f)}return{isOnBar:function(a){return c===a.first},changeNotesSize:function(a,c,d){for(var e=0;e<c.length;e++)b[a][c[e]].size=d},changeNotesColor:function(a,c,d){for(var e=0;e<c.length;e++)b[a][c[e]].color=d},drawAllOrnaments:function(){for(var a=0<=navigator.userAgent.toLowerCase().indexOf("firefox"),c=0;c<b.length;c++)for(var e=
0;e<b[c].length;e++){if("1.0"!==b[c][e].size&&!a){var f=d(c,[e]);f[0].style.transformOrigin="50% 50%";f[0].style.transform="scale("+b[c][e].size+")"}"black"!==b[c][e].color&&(f=d(c,[e]),f[0].setAttribute("fill",b[c][e].color))}}}}function f(){a.innerHTML="";var c=new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.SVG);context=c.getContext();c.resize(a.clientWidth,a.clientHeight);context.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return context}function d(a,c){for(var b=document.querySelectorAll("#vf-"+
l[a].attrs.id+" g.vf-notehead path"),d=[],e=0;e<c.length;e++)d.push(b[c[e]]);return d}function c(a){var c=h.getBar(a);return a-c.first}var a=e,h=null,l=[],k=0,m=null;return{setPiece:function(a){h=a;k=0},setFocus:function(a){k=a},display:function(){var a=f(),c=new Vex.Flow.Stave(4,64,a.width-8),d=h.getBar(k);c.addClef(d.clef).addTimeSignature(d.time).addKeySignature(VFUtility.toVFKeySignature(d.key));c.setMeasure(h.getData().bars.indexOf(d)+1);c.setContext(a).draw();l=[];for(var e={},z=0;z<d.verticals.length;z++)l.push(VFUtility.prepareStaveNote(d.key,
d.clef,d.verticals[z],e));e=Vex.Flow.Beam.generateBeams(l);Vex.Flow.Formatter.FormatAndDraw(a,c,l);e.forEach(function(c){c.setContext(a).draw()});null!==m&&m.isOnBar(d)?m.drawAllOrnaments():m=new b(d)},changeNotesSize:function(a,b,e){e=void 0===e?"1.0":e;if(!(0<=navigator.userAgent.toLowerCase().indexOf("firefox"))){a=c(a);for(var f=d(a,b),g=0;g<f.length;g++)f[g].style.transformOrigin="50% 50%",f[g].style.transform="scale("+e+")";m.changeNotesSize(a,b,e)}},changeNotesColor:function(a,b,e){e=void 0===
e?"black":e;a=c(a);for(var f=d(a,b),g=0;g<f.length;g++)f[g].setAttribute("fill",e);m.changeNotesColor(a,b,e)}}}var MusicStorageManager=function(){return{getPiece:function(e){"default"===e&&(e=Locale.getApplicationTitle("en")+e);e=localStorage.getItem("_piece_"+e);return null===e?null:Piece.createFromString(e)},setPiece:function(e){e=e.getData();var b="_piece_"+e.id;"default"===e.id&&(b="_piece_"+Locale.getApplicationTitle("en")+e.id);localStorage.setItem(b,JSON.stringify(e))}}}();
function MusicViewer(e){function b(){c.innerHTML="";var a=Vex.Flow.Renderer.Backends.SVG;"CANVAS"===c.tagName.toUpperCase()&&(a=Vex.Flow.Renderer.Backends.CANVAS);a=new Vex.Flow.Renderer(c,a);k=a.getContext();a.resize(c.clientWidth,c.clientHeight);k.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return k}function f(b,d,e){d=void 0===d?0:d;e=void 0===e?0:e;var f={"C\u266f":7,"b\u266d":5,"E\u266d":3,"c\u266f":4,d:1,c:3,"a\u266f":7,F:1,B:5,D:2,"G\u266d":6,"B\u266d":2,"g\u266f":5,e:1,"C\u266d":7,
"F\u266f":6,b:2,G:1,"a\u266d":7,E:4,a:0,C:0,"A\u266d":4,"f\u266f":3,"d\u266f":6,g:2,A:3,f:4,"D\u266d":5,"e\u266d":6};d=(0===d?c.clientWidth:d)-8;var g=0===e?c.clientHeight:e;e=Math.floor(g/160);for(var g=40+.33*(g-160*e),h=a.getData(),k=[],n=0;n<e;n++)k.push({height:160,staves:[]});for(n=0;n<e&&b<h.bars.length;n++){for(var m=[],p="",u="",x="",q=b;q<h.bars.length;q++){var v=h.bars[q],r={clef:"",key:"",time:"",verticals:v.verticals.length,size:0};v.clef!==p&&(p=r.clef=v.clef,r.size+=25);v.key!==u&&
(u=r.key=v.key,r.size+=8*f[v.key]);v.time!==x&&(x=r.time=v.time,r.size+=14);r.size+=50*r.verticals;m.push(r)}u=0;p=h.bars.length-b;for(q=b;q<h.bars.length;q++)if(u+=m[q-b].size,u>d){p=q>b?q-b:1;break}for(q=u=0;q<p;q++)u+=m[q].size;for(q=x=0;q<p;q++)l=v=q+b,r=m[q].size/u*d,k[n].staves.push({barIndex:v,left:x+4,width:r}),x+=r;b+=p}return{rows:k,staveOffsetTop:g}}function d(c){var b=a.getData();c=0==c?b.bars.length-1:c-1;for(var d=0,e=0;e<b.bars.length;e++){for(var h=d,g=f(d),k=0;k<g.rows.length;k++)for(var l=
0;l<g.rows[k].length;l++){if(c===g.rows[k][l].barIndex)return 0==k+l?h:d;d=g.rows[k][l].barIndex}d+=1}}var c=e,a=null,h=0,l=0,k=null,m=null;b();return{setPiece:function(c){a=c},setFirstBar:function(a){h=a},display:function(){b();var c=a.getData(),d=f(h),e=d.staveOffsetTop;m=d;for(var l=0;l<d.rows.length;l++){for(var z="",B="",C="",w=0;w<d.rows[l].staves.length;w++){var t=c.bars[d.rows[l].staves[w].barIndex],A=new Vex.Flow.Stave(d.rows[l].staves[w].left,e,d.rows[l].staves[w].width);0==w&&A.setMeasure(d.rows[l].staves[w].barIndex+
1);t.clef!==z&&(z=t.clef,A.addClef(t.clef));t.key!==B&&(B=t.key,A.addKeySignature(VFUtility.toVFKeySignature(t.key)));t.time!==C&&(C=t.time,A.addTimeSignature(t.time));A.setContext(k).draw();for(var u=[],x={},q=0;q<t.verticals.length;q++)u.push(VFUtility.prepareStaveNote(t.key,t.clef,t.verticals[q],x));t=Vex.Flow.Beam.generateBeams(u);Vex.Flow.Formatter.FormatAndDraw(k,A,u);t.forEach(function(a){a.setContext(k).draw()})}e+=d.rows[l].height}},getLastBar:function(){return l},getCurrentLayout:function(){return m},
getFirstBarInPreviousPage:d,getFirstBarInLastPage:function(){return d(0)}}}
var Note=function(){function e(c){var a={A:[0,1],"B\ud834\udd2b":[0,1],"G\ud834\udd2a":[0,1],"A\u266f":[0,2],"B\u266d":[0,2],B:[0,3],"A\ud834\udd2a":[0,3],"C\u266d":[1,3],C:[1,4],"D\ud834\udd2b":[1,4],"B\u266f":[0,4],"C\u266f":[1,5],"D\u266d":[1,5],D:[1,6],"E\ud834\udd2b":[1,6],"C\ud834\udd2a":[1,6],"D\u266f":[1,7],"E\u266d":[1,7],"F\ud834\udd2b":[1,7],E:[1,8],"F\u266d":[1,8],"D\ud834\udd2a":[1,8],F:[1,9],"G\ud834\udd2b":[1,9],"E\u266f":[1,9],"F\u266f":[1,10],"G\u266d":[1,10],G:[1,11],"A\ud834\udd2b":[1,
11],"F\ud834\udd2a":[1,11],"G\u266f":[1,12],"A\u266d":[1,12]};c=b(c);var d=c.natural+c.accidental;return a.hasOwnProperty(d)?(a=a[d],a[1]+12*(c.octave-a[0])):-1}function b(c){var a={natural:"",octave:-1,accidental:""};if(0>=c.length)return a;a.natural=c[0];a.octave=parseInt(c.substring(c.length-1,c.length));a.accidental="";a.accidentalASCII="";2<c.length&&(1==c.indexOf("\u266d")?(a.accidental="\u266d",a.accidentalASCII="b"):1==c.indexOf("\u266f")?(a.accidental="\u266f",a.accidentalASCII="#"):1==c.indexOf("\ud834\udd2b")?
(a.accidental="\ud834\udd2b",a.accidentalASCII="bb"):1==c.indexOf("\ud834\udd2a")&&(a.accidental="\ud834\udd2a",a.accidentalASCII="##"));return a}function f(c,a){var b=d[c],e="";"\u266d"==b.sharpflat&&"BEADGCF".indexOf(a)<b.amount?e="\u266d":"\u266f"==b.sharpflat&&"FCGDAEB".indexOf(a)<b.amount&&(e="\u266f");return e}var d={"D\u266d":{index:0,sharpflat:"\u266d",amount:5},"G\u266f":{index:1,sharpflat:"\u266f",amount:8},"b\u266d":{index:2,sharpflat:"\u266d",amount:5},"C\u266d":{index:3,sharpflat:"\u266d",
amount:7},e:{index:4,sharpflat:"\u266f",amount:1},"C\u266f":{index:5,sharpflat:"\u266f",amount:7},B:{index:6,sharpflat:"\u266f",amount:5},g:{index:7,sharpflat:"\u266d",amount:2},f:{index:8,sharpflat:"\u266d",amount:4},"F\u266d":{index:9,sharpflat:"\u266d",amount:8},a:{index:10,sharpflat:"\u266f",amount:0},G:{index:11,sharpflat:"\u266f",amount:1},"B\u266d":{index:12,sharpflat:"\u266d",amount:2},"e\u266f":{index:13,sharpflat:"\u266f",amount:8},"a\u266f":{index:14,sharpflat:"\u266f",amount:7},"d\u266d":{index:15,
sharpflat:"\u266d",amount:8},d:{index:16,sharpflat:"\u266d",amount:1},"F\u266f":{index:17,sharpflat:"\u266f",amount:6},"g\u266f":{index:18,sharpflat:"\u266f",amount:5},C:{index:19,sharpflat:"\u266f",amount:0},D:{index:20,sharpflat:"\u266f",amount:2},"A\u266d":{index:21,sharpflat:"\u266d",amount:4},A:{index:22,sharpflat:"\u266f",amount:3},"E\u266d":{index:23,sharpflat:"\u266d",amount:3},"f\u266f":{index:24,sharpflat:"\u266f",amount:3},c:{index:25,sharpflat:"\u266d",amount:3},b:{index:26,sharpflat:"\u266f",
amount:2},F:{index:27,sharpflat:"\u266d",amount:1},E:{index:28,sharpflat:"\u266f",amount:4},"G\u266d":{index:29,sharpflat:"\u266d",amount:6},"c\u266f":{index:30,sharpflat:"\u266f",amount:4},"e\u266d":{index:31,sharpflat:"\u266d",amount:6},"a\u266d":{index:32,sharpflat:"\u266d",amount:7},"d\u266f":{index:33,sharpflat:"\u266f",amount:6}};return{flat:"\u266d",sharp:"\u266f",flatflat:"\ud834\udd2b",sharpsharp:"\ud834\udd2a",getNoteOrder:e,getNoteFrequency:function(c){c=e(c);"DoubleBass"===Locale.getApplicationTitle("en")&&
(c-=12);return 0>c?0:440*Math.pow(Math.pow(2,1/12),c-49)},getNoteDetail:b,getDefaultAccidental:f,getDefaultAccidentalASCII:function(c,a){return f(c,a).replace("\u266f","#").replace("\u266d","b")},getFirstNoteInKey:function(c){c=c.substring(0,1);return 0<="GAB".indexOf(c)?c+"3":c+"4"}}}(),PDFConverter=function(e,b){function f(){var b=d.querySelectorAll("div.page");h+=1;h>=b.length?c(a):(a.addPage(),a.addHTML(b[h],f))}var d=e,c=b,a=null,h=0;return{convert:function(){var b=d.querySelectorAll("div.page");
0>=b.length?c(null):(a=new jsPDF("p","pt","a4"),h=0,a.addHTML(b[0],f))}}},PDFPage=function(){function e(){LoadingIconManager.show();var b=document.querySelector("body > div#pdfRenderer");b.style.display="block";var d=new PDFRenderer(b),c=MusicStorageManager.getPiece(App.getDefaultPieceId());null===c?alert("Cannot show PDF"):(d.render(c),(new PDFConverter(b,function(a){b.style.display="none";window.top.pdfdata=a.output("arraybuffer");document.querySelector("body > div#container > div#wrapper").innerHTML=
'<embed src="/pdf.js/viewer.html">'})).convert(c))}var b=function(){return{onComplete:function(){LoadingIconManager.hide()},onerror:onerror}}();return{initialize:function(f){window.top.PDFJS=b;LoadingIconManager.show();document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){window.location=App.getPiecePath()});e();f=App.getPiecePath();history.replaceState("","",f)},draw:function(){},getPath:function(){return"pdf.html"}}}(),PDFRenderer=function(e){return{render:function(b){e.innerHTML=
"";for(var f=-1,d=-1,c=0;8>c;c++){d+=1;f+=1;if(f>=b.getData().bars.length)break;var a;a=d;var h=document.createElement("div");h.classList.add("page");h.innerHTML='<div class="header"></div><div class="title XXX"></div><canvas class="music"></canvas><div class="footer"></div>'.replace("XXX",0===a?"":"hide");e.appendChild(h);a=h;a.querySelector("div.title").innerHTML=Locale.getTranslation(b.getData().descriptions);a.querySelector("div.footer").innerHTML=Locale.getPrintFooter();a=new MusicViewer(a.querySelector("canvas.music"));
a.setPiece(b);a.setFirstBar(f);a.display();f=a.getLastBar()}}}},Piece=function(){function e(b){function e(c){for(var a=0;a<d.bars.length;a++)if(d.bars[a].first<=c&&c<d.bars[a].first+d.bars[a].verticals.length)return d.bars[a];return null}var d=JSON.parse(b);return{getData:function(){return d},getBar:e,getPreBar:function(c){c=e(c);return null===c?null:e(c.first-1)},getNextBar:function(c){c=e(c);return null===c?null:e(c.first+c.verticals.length)},getTotalVerticals:function(){var c=d.bars[d.bars.length-
1];return c.first+c.verticals.length}}}return{createFromString:function(b){return new e(b)}}}(),SharePage=function(){function e(d){var c=d.target.id;c in f?(d=f[c].replace("URL",encodeURIComponent(b.url)).replace("DESCRIPTION",encodeURIComponent(b.description)).replace("VIA","Metronome"),window.open(d,"_blank")):"mail"==c?(d="mailto:?subject="+encodeURIComponent(b.description)+"&body="+encodeURIComponent(b.url),window.open(d,"_blank")):"link"==d.target.id&&(d=document.querySelector("body > input#copy"),
d.classList.remove("hidden"),d.value=b.url,d.select(),document.execCommand("copy"),d.classList.add("hidden"));window.location=App.getPiecePath()}var b={url:"",description:""},f={qq:"http://v.t.qq.com/share/share.php?url=URL&title=DESCRIPTION",weibo:"http://service.weibo.com/share/share.php?url=URL&title=DESCRIPTION",qzone:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=URL&title=DESCRIPTION",facebook:"https://www.facebook.com/sharer/sharer.php?u=URL&t=DESCRIPTION",twitter:"https://twitter.com/intent/tweet?text=DESCRIPTION&url=URL&via=VIA"};
return{initialize:function(d){d=App.getDefaultPieceId();var c=MusicStorageManager.getPiece(d);document.querySelector("body > div#container > div#share > div#title").innerHTML=Locale.getSharingTitle(c);c=App.getHost()+App.getPiecePath();history.replaceState("","",c);b.url=c;c=MusicStorageManager.getPiece(d);b.description=Locale.getPieceDescription(c)+", "+Locale.getApplicationTitle()+", "+Locale.getProjectName();d=document.querySelectorAll("body > div#container > div#share > div#services > div.service");
for(c=0;c<d.length;c++)d[c].addEventListener("click",e);document.querySelector("body > div#container > div#controls > div#ok").addEventListener("click",function(){window.location=App.getPiecePath()})},draw:function(){},getPath:function(){return"share.html"}}}(),StringInstrumentSimulator=function(){function e(){if(null!=b)return!0;if("AudioContext"in window)b=new AudioContext;else if("webkitAudioContext"in window)b=new webkitAudioContext;else return b=null,!1;f=b.createGain();f.gain.value=0;f.connect(b.destination);
return!0}var b=null,f=null,d=[];return{play:function(c){e();for(var a=0;a<c.length;a++)if(!(0>=c[a])){var h=b.createOscillator();h.frequency.value=c[a];var l=h,k=Math.PI,m=new Float32Array(12),g=new Float32Array(12),n=[.49,.995,.94,.425,.48,0,.365,.04,.085,0,.09,0],k=[0,0,k/2,0,k/2,0,k/2,0,k/2,0,k/2,0];m[0]=0;g[0]=0;for(var p=1;12>p;p++)m[p]=n[p]*n[0]*Math.cos(k[p]),g[p]=n[p]*n[0]*Math.sin(k[p]);m=b.createPeriodicWave(g,m);l.setPeriodicWave(m);h.connect(f);h.start(0);d.push(h)}f.gain.linearRampToValueAtTime(0,
b.currentTime);f.gain.linearRampToValueAtTime(.5,b.currentTime+.05)},stop:function(){e();f.gain.linearRampToValueAtTime(.5,b.currentTime);f.gain.linearRampToValueAtTime(0,b.currentTime+.05);setTimeout(function(){for(var c=0;c<d.length;c++){var a=d[c];a.stop(0);a.disconnect(f)}d=[]},50)},playAndStop:function(c,a,b){}}}(),VFUtility=function(){function e(b){b=Note.getNoteDetail(b);return b.natural+b.accidentalASCII+"/"+b.octave}return{toVFKeySignature:function(b){b!==b.toUpperCase()&&(b=b.toUpperCase()+
"m");return b=b.replace(Note.flat,"b").replace(Note.sharp,"#")},prepareStaveNote:function(b,f,d,c){for(var a,h,l,k=[],m=0;m<d.notes.length;m++)k.push(e(d.notes[m]));f=new Vex.Flow.StaveNote({clef:f,keys:k,duration:d.duration});if("r"!==d.duration.substr(-1))for(m=0;m<d.notes.length;m++)a:{var g=b,k=f,n=m,p=c;l=k.keys[n];var y=l.indexOf("/");a=l.substring(0,1);h=parseInt(l.substring(y+1));l=l.substring(1,y);y=a+h;h=!1;if(p.hasOwnProperty(y))if(p[y]==l)break a;else h=!0;p[y]=l;"bb"==l?k.addAccidental(n,
new Vex.Flow.Accidental("bb")):"##"==l?k.addAccidental(n,new Vex.Flow.Accidental("##")):(a=Note.getDefaultAccidentalASCII(g,a),"#"==a?"#"==l?h&&k.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==l?k.addAccidental(n,new Vex.Flow.Accidental("b")):k.addAccidental(n,new Vex.Flow.Accidental("n")):"b"==a?"#"==l?k.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==l?h&&k.addAccidental(n,new Vex.Flow.Accidental("b")):k.addAccidental(n,new Vex.Flow.Accidental("n")):"#"==l?k.addAccidental(n,new Vex.Flow.Accidental("#")):
"b"==l?k.addAccidental(n,new Vex.Flow.Accidental("b")):h&&k.addAccidental(n,new Vex.Flow.Accidental("n")))}b=d.duration;"dd"==b.substring(b.length-2)?f.addDotToAll().addDotToAll():(d=d.duration,"d"==d.substring(d.length-1)&&f.addDotToAll());return f}}}(),App=function(){function e(){f.draw()}var b={},f=null;return{initialize:function(d){d=void 0===d?{}:d;Header.initialize();for(var c=window.location.pathname,a=window.location.search,a=("?"===a[0]?a.substr(1):a).split("&"),h=0;h<a.length;h++){var l=
a[h].split("=");d[decodeURIComponent(l[0])]=decodeURIComponent(l[1]||"")}d.lastPage=sessionStorage.lastPage||null;b=d;f=0===c.indexOf("/v1/"+CatalogPage.getPath())?CatalogPage:0===c.indexOf("/v1/"+AboutPage.getPath())?AboutPage:0===c.indexOf("/v1/"+PDFPage.getPath())?PDFPage:0===c.indexOf("/v1/"+SharePage.getPath())?SharePage:IndexPage;Header.highlight(f);f.initialize(d);sessionStorage.setItem("lastPage","/v1/"+f.getPath());window.addEventListener("resize",e)},getParams:function(){return b},resize:e,
getHost:function(){var b=window.location.href;return b.substring(0,b.indexOf("/",8))},getPagePath:function(b){return"/v1/"+(void 0===b?null:b).getPath()},getPiecePath:function(b){b=void 0===b?null:b;b=null===b?App.getDefaultPieceId():b.getData().id;return App.getPagePath(IndexPage)+"?p="+b},getPiecesPath:function(){return"/v1/pieces/"},getDefaultPieceId:function(){var d=b,c="default";d.hasOwnProperty("p")?c=d.p:"lastPieceId"in sessionStorage&&(c=sessionStorage.lastPieceId);return c}}}();
