var AboutPage=function(){return{initialize:function(b){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){window.location=App.getPagePath(IndexPage)+App.getLastConfigInCurrentSessionInURLParams()})},draw:function(){},getPath:function(){return"about.html"}}}(),AdManager=function(){(function(){for(var b=document.querySelectorAll("body > div#ad > div"),c=0;c<b.length;c++)b[c].addEventListener("click",function(){window.location="https://www.facebook.com/unicef"})})()}(),
AJAX=function(){return{GET:function(b){var c=b.url,d=b.onSuccess||null,a=b.onFailure||null,h=new XMLHttpRequest;h.responseType=b.responseType||"";h.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==d&&d(this.response):null!==a&&a(this.status))};h.open("GET",c,!0);h.send()}}}(),AudioPlayer=function(){function b(b,c){AJAX.GET({url:b,responseType:"arraybuffer",onSuccess:function(b){d.decodeAudioData(b,function(b){a[c]=b})}})}function c(a){if(null===a)return!1;var b=d.createBufferSource();
b.buffer=a;b.connect(d.destination);b.start(0);return!0}var d=null,a={first:null,other:null};return{initialize:function(){window.AudioContext=window.AudioContext||window.webkitAudioContext;d=new AudioContext;b(App.getRootPath()+"sound/first.wav","first");b(App.getRootPath()+"sound/other.wav","other")},playFirst:function(){return c(a.first)},playOther:function(){return c(a.other)}}}(),Config=function(){return{fromURLParams:function(b){var c={};c.top=parseInt(b.t)||3;c.bottom=parseInt(b.b)||2;c.tempo=
parseInt(b.p)||12;return c},toURLParams:function(b){var c;c="?t="+b.top;c+="&b="+b.bottom;return c+="&p="+b.tempo},fromLocalStorage:function(){var b=localStorage.getItem("polyrhythm_config");return null!==b?JSON.parse(b):null},saveToLocalStorage:function(b){localStorage.setItem("polyrhythm_config",JSON.stringify(b))},isValidConfig:function(b){function c(a){return 2>a||9<a?!1:!0}function d(a){return 1>a||120<a?!1:!0}return null===b?!1:c(b.top)&&c(b.bottom)&&d(b.tempo)},getDefaultConfig:function(){return{top:3,
bottom:2,tempo:12}},isSameConfig:function(b,c){return null===b||null===c?!1:b.top===c.top&&b.bottom===c.bottom&&b.tempo===c.tempo}}}(),Header=function(){function b(){window.location=App.getPagePath(AboutPage)}function c(){d=document.querySelector("div#header > div#controls > div.control#index");d.addEventListener("click",function(){window.location=App.getPagePath(IndexPage)+App.getLastConfigInCurrentSessionInURLParams()});a=document.querySelector("div#header > div#controls > div.control#share");a.addEventListener("click",
function(){window.location=App.getPagePath(SharePage)});document.querySelector("div#header > div#title  > div#text").addEventListener("click",b);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",b)}var d=null,a=null;return{initialize:function(){c();document.querySelector("div#header > div#title  > div#text").innerHTML=Locale.getApplicationTitle()},highlight:function(b){a.classList.remove("highlighted");b===SharePage?a.classList.add("highlighted"):d.classList.add("highlighted")}}}(),
IndexPage=function(){function b(){window.history.replaceState({},"",App.getPagePath(IndexPage)+Config.toURLParams(a));sessionStorage.setItem("polyrhythm_urlparams",Config.toURLParams(a));document.querySelector("body > div#container > div#music > div#header > div#title").innerHTML=Locale.getConfigDescription(a);var b=Config.fromLocalStorage(),e=document.querySelector("body > div#container > div#music > div#header > div#controls > div.control#load");null===b||Config.isSameConfig(a,b)?e.classList.add("hidden"):
e.classList.remove("hidden")}function c(c){if("topMore"===c.target.id){if(9===a.top)return;a.top+=1}if("topLess"===c.target.id){if(2===a.top)return;--a.top}if("bottomMore"===c.target.id){if(9===a.bottom)return;a.bottom+=1}if("bottomLess"===c.target.id){if(2===a.bottom)return;--a.bottom}var e=Math.floor(240/Math.max(a.top,a.bottom));a.tempo>e&&(a.tempo=e);"minusminus"===c.target.id&&(a.tempo=1>a.tempo-10?1:a.tempo-10);"minus"===c.target.id&&(1>a.tempo-1?a.tempo=1:--a.tempo);"plusplus"===c.target.id&&
(a.tempo=a.tempo+10>e?e:a.tempo+10);"plus"===c.target.id&&(a.tempo=a.tempo+1>e?e:a.tempo+1);document.querySelector("body > div#container > div#settings > div#rhythms > div#value").innerHTML=a.top+":"+a.bottom;f.setConfig(a);f.draw();b();document.querySelector("body > div#container > div#settings > div#tempo > div#value").innerHTML=a.tempo}function d(){f.draw()}var a=null,h=!1,f=null,k=function(){function b(a,c){return c?b(c,a%c):a}function c(){0===l%a.top&&q(l/a.top);0===l%a.bottom&&k(l/a.bottom);
l=(l+1)%m;n=setTimeout(c,p)}function d(a,b,c){a.setAttribute("fill",b);a.style.transformOrigin="50% 50%";a.style.transform="scale("+c+")"}function k(a){h||AudioPlayer.playFirst();var b=f.getStaveNoteHeadElement("top",a),c=f.getStaveNoteStemElement("top",a);null!==b&&null!==c&&(d(b,"green",1.8),c.setAttribute("stroke","green"),setTimeout(function(){d(b,"black",1);c.setAttribute("stroke","black")},200))}function q(a){h||AudioPlayer.playOther();var b=f.getStaveNoteHeadElement("bottom",a),c=f.getStaveNoteStemElement("bottom",
a);null!==b&&null!==c&&(d(b,"red",1.8),c.setAttribute("stroke","red"),setTimeout(function(){d(b,"black",1);c.setAttribute("stroke","black")},200))}var n=null,p=Number.MAX_VALUE,l=0,m=Number.MAX_VALUE;return{play:function(){var e=a.top,d=a.bottom;m=e*(d/b(e,d));p=60/(m*a.tempo)*1E3;l=0;c()},stop:function(){clearTimeout(n);n=null;p=Number.MAX_VALUE;l=0;m=Number.MAX_VALUE}}}();return{initialize:function(g){AudioPlayer.initialize();a=Config.fromURLParams(g);Config.isValidConfig(a)||(alert("Invalid config. Revert to default."),
a=Config.getDefaultConfig());document.querySelector("body > div#container > div#settings > div#rhythms > div#value").innerHTML=a.top+":"+a.bottom;document.querySelector("body > div#container > div#settings > div#tempo > div#value").innerHTML=a.tempo;f=new Player(document.querySelector("body > div#container > div#music  > div#sheet"));document.querySelector("body > div#container > div#music > div#header > div#controls > div.control#load");f.setConfig(a);b();g=document.querySelectorAll("body > div#container > div#settings div.control");
for(var e=0;e<g.length;e++)g[e].addEventListener("click",c);document.querySelector("body > div#container > div#music > div#header > div#controls > div.control#load").addEventListener("click",function(){a=Config.fromLocalStorage();f.setConfig(a);b();d()});document.querySelector("body > div#container > div#music > div#header > div#controls > div.control#mute").addEventListener("click",function(a){h=a.target.classList.contains("muted");a.target.classList.toggle("muted")});document.querySelector("body > div#container > div#music > div#header > div#controls > div.control#play").addEventListener("click",
function(b){Config.saveToLocalStorage(a);document.querySelector("body > div#container > div#music > div#header > div#controls > div.control#load").classList.add("hidden");var c=b.target.classList.contains("playing");b.target.classList.toggle("playing");c?(k.stop(),document.querySelector("body > div#container > div#settings").classList.remove("hidden")):(k.play(),document.querySelector("body > div#container > div#settings").classList.add("hidden"))});d()},draw:d,getPath:function(){return"index.html"}}}(),
Locale=function(){function b(b,c){var e;void 0===c&&(c=a);e=c in b?b[c]:b.en;for(var d=2;d<arguments.length;d++)e=e.replace("{"+(d-1)+"}",arguments[d]);return e}function c(a,c){return b(k,c,a.top,a.bottom,a.tempo)}var d=["en","zh-cn"],a="en",h={en:"HeliMusic","zh-cn":"\u55e8\u4e50"},f={en:"PolyRhythm","zh-cn":"\u590d\u8282\u594f"},k={en:"PolyRhythm {1}:{2} in tempo {3}","zh-ch":"\u590d\u8282\u594f{1}:{2}\u8282\u62cd{3}"},g={en:"Share <b>{1}</b> to your friends using buttons above or your browser's sharing functions!",
"zh-cn":"\u4f7f\u7528\u4e0a\u9762\u7684\u6309\u94ae\u6216\u8005\u6d4f\u89c8\u5668\u7684\u5206\u4eab\u529f\u80fd\u628a{1}\u5206\u4eab\u7ed9\u4f60\u7684\u670b\u53cb\uff01"};(function(){if("language"in localStorage&&0<=d.indexOf(localStorage.language))a=localStorage.language;else{var b=navigator.languages&&navigator.languages[0]||navigator.language||navigator.userLanguage,b=b.toLowerCase();a=0<=d.indexOf(b)?b:"en"}})();return{getProjectName:function(a){return b(h,a)},getApplicationTitle:function(a){return b(f,
a)},getSharingTitle:function(a,d){return b(g,d,c(a))},getConfigDescription:c}}();
function Player(b){function c(){d.innerHTML="";var a=new Vex.Flow.Renderer(d,Vex.Flow.Renderer.Backends.SVG);context=a.getContext();a.resize(d.clientWidth,d.clientHeight);context.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return context}var d=b,a=null,h=[],f=[];return{setConfig:function(b){a=b},draw:function(){var b=c(),g=b.width/10;320<b.width&&480>=b.width?g=b.width/16:200<b.width&&320>=b.width?g=b.width/20:200>=b.width&&(g=4);g=new Vex.Flow.Stave(g,16,b.width-3*g);g.addClef("treble");
g.setContext(b).draw();var e=d.querySelectorAll("svg path"),e=e[1].outerHTML.replace(/stroke-width="1"/i,'stroke-width="1.25" stroke="black"')+e[4].outerHTML.replace(/stroke-width="1"/i,'stroke-width="1.25" stroke="black"');d.querySelector("svg").innerHTML=e;h=[];for(e=0;e<a.top;e++)h.push(new Vex.Flow.StaveNote({clef:"treble",keys:["d/5"],duration:"8",stem_direction:1}));f=[];for(e=0;e<a.bottom;e++)f.push(new Vex.Flow.StaveNote({clef:"treble",keys:["e/4"],duration:"8",stem_direction:-1}));e=[new Vex.Flow.Beam(h)];
Vex.Flow.Formatter.FormatAndDraw(b,g,h);e.forEach(function(a){a.setContext(b).draw()});e=[new Vex.Flow.Beam(f)];Vex.Flow.Formatter.FormatAndDraw(b,g,f);e.forEach(function(a){a.setContext(b).draw()})},getStaveNoteHeadElement:function(b,c){"bottom"===b&&(c+=a.top);var d=document.querySelectorAll("g.vf-stavenote > g.vf-note > g.vf-notehead > path");return d.length>c?d[c]:null},getStaveNoteStemElement:function(b,c){c+=2;"bottom"===b&&(c+=a.top+1);var d=document.querySelectorAll("svg > path");return d.length>
c?d[c]:null}}}
var SharePage=function(){function b(a){var b=a.target.id;b in d?(a=d[b].replace("URL",encodeURIComponent(c.url)).replace("DESCRIPTION",encodeURIComponent(c.description)).replace("VIA","Metronome"),window.open(a,"_blank")):"mail"==b?(a="mailto:?subject="+encodeURIComponent(c.description)+"&body="+encodeURIComponent(c.url),window.open(a,"_blank")):"link"==a.target.id&&(a=document.querySelector("body > input#copy"),a.classList.remove("hidden"),a.value=c.url,a.select(),document.execCommand("copy"),a.classList.add("hidden"));
window.location=App.getPagePath(IndexPage)+App.getLastConfigInCurrentSessionInURLParams()}var c={url:"",description:""},d={qq:"http://v.t.qq.com/share/share.php?url=URL&title=DESCRIPTION",weibo:"http://service.weibo.com/share/share.php?url=URL&title=DESCRIPTION",qzone:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=URL&title=DESCRIPTION",facebook:"https://www.facebook.com/sharer/sharer.php?u=URL&t=DESCRIPTION",twitter:"https://twitter.com/intent/tweet?text=DESCRIPTION&url=URL&via=VIA"};
return{initialize:function(a){a=App.getPagePath(IndexPage)+App.getLastConfigInCurrentSessionInURLParams();history.replaceState("","",a);a=Config.fromURLParams(App.getParams());document.querySelector("body > div#container > div#share > div#title").innerHTML=Locale.getSharingTitle(a);c.url=window.location.href;c.description=Locale.getConfigDescription(a)+", "+Locale.getApplicationTitle()+", "+Locale.getProjectName();a=document.querySelectorAll("body > div#container > div#share > div#services > div.service");
for(var d=0;d<a.length;d++)a[d].addEventListener("click",b);document.querySelector("body > div#container > div#controls > div#ok").addEventListener("click",function(){window.location=App.getPagePath(IndexPage)+App.getLastConfigInCurrentSessionInURLParams()})},draw:function(){},getPath:function(){return"share.html"}}}(),App=function(){function b(){d.draw()}var c={},d=null;return{initialize:function(a){a=void 0===a?{}:a;Header.initialize();for(var h=window.location.pathname,f=window.location.search,
f=("?"===f[0]?f.substr(1):f).split("&"),k=0;k<f.length;k++){var g=f[k].split("=");a[decodeURIComponent(g[0])]=decodeURIComponent(g[1]||"")}a.lastPage=sessionStorage.lastPage||null;c=a;d=0===h.indexOf("/pr/"+AboutPage.getPath())?AboutPage:0===h.indexOf("/pr/"+SharePage.getPath())?SharePage:IndexPage;Header.highlight(d);d.initialize(a);sessionStorage.setItem("lastPage","/pr/"+d.getPath());window.addEventListener("resize",b)},getParams:function(){return c},resize:b,getHost:function(){var a=window.location.href;
return a.substring(0,a.indexOf("/",8))},getLastConfigInCurrentSessionInURLParams:function(){return sessionStorage.getItem("polyrhythm_urlparams")||""},getRootPath:function(){return"/pr/"},getPagePath:function(a){return"/pr/"+(void 0===a?null:a).getPath()}}}();
