var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(d,a,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");d!=Array.prototype&&d!=Object.prototype&&(d[a]=f.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var a=0;return $jscomp.iteratorPrototype(function(){return a<d.length?{done:!1,value:d[a++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.polyfill=function(d,a,f,c){if(a){f=$jscomp.global;d=d.split(".");for(c=0;c<d.length-1;c++){var e=d[c];e in f||(f[e]={});f=f[e]}d=d[d.length-1];c=f[d];a=a(c);a!=c&&null!=a&&$jscomp.defineProperty(f,d,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.from",function(d){return d?d:function(a,d,c){$jscomp.initSymbolIterator();d=null!=d?d:function(a){return a};var e=[],b=a[Symbol.iterator];if("function"==typeof b)for(a=b.call(a);!(b=a.next()).done;)e.push(d.call(c,b.value));else for(var b=a.length,f=0;f<b;f++)e.push(d.call(c,a[f]));return e}},"es6-impl","es3");$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();var a=d[Symbol.iterator];return a?a.call(d):$jscomp.arrayIterator(d)};
$jscomp.owns=function(d,a){return Object.prototype.hasOwnProperty.call(d,a)};
$jscomp.polyfill("WeakMap",function(d){function a(a){$jscomp.owns(a,c)||$jscomp.defineProperty(a,c,{value:{}})}function f(b){var c=Object[b];c&&(Object[b]=function(b){a(b);return c(b)})}if(function(){if(!d||!Object.seal)return!1;try{var a=Object.seal({}),b=Object.seal({}),c=new d([[a,2],[b,3]]);if(2!=c.get(a)||3!=c.get(b))return!1;c["delete"](a);c.set(b,4);return!c.has(a)&&4==c.get(b)}catch(m){return!1}}())return d;var c="$jscomp_hidden_"+Math.random().toString().substring(2);f("freeze");f("preventExtensions");
f("seal");var e=0,b=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};b.prototype.set=function(b,e){a(b);if(!$jscomp.owns(b,c))throw Error("WeakMap key fail: "+b);b[c][this.id_]=e;return this};b.prototype.get=function(b){return $jscomp.owns(b,c)?b[c][this.id_]:void 0};b.prototype.has=function(b){return $jscomp.owns(b,c)&&$jscomp.owns(b[c],this.id_)};b.prototype["delete"]=
function(b){return $jscomp.owns(b,c)&&$jscomp.owns(b[c],this.id_)?delete b[c][this.id_]:!1};return b},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(d){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),a=new d($jscomp.makeIterator([[b,"s"]]));if("s"!=a.get(b)||1!=a.size||a.get({x:4})||a.set({x:4},"t")!=a||2!=a.size)return!1;var c=a.entries(),e=c.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=c.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!c.next().done?!1:!0}catch(n){return!1}}())return d;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var a=new WeakMap,f=function(a){this.data_={};this.head_=b();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};f.prototype.set=function(b,a){var e=c(this,b);e.list||(e.list=this.data_[e.id]=[]);e.entry?e.entry.value=a:(e.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:b,value:a},e.list.push(e.entry),this.head_.previous.next=e.entry,this.head_.previous=e.entry,this.size++);return this};f.prototype["delete"]=
function(b){b=c(this,b);return b.entry&&b.list?(b.list.splice(b.index,1),b.list.length||delete this.data_[b.id],b.entry.previous.next=b.entry.next,b.entry.next.previous=b.entry.previous,b.entry.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=b();this.size=0};f.prototype.has=function(b){return!!c(this,b).entry};f.prototype.get=function(b){return(b=c(this,b).entry)&&b.value};f.prototype.entries=function(){return e(this,function(b){return[b.key,
b.value]})};f.prototype.keys=function(){return e(this,function(b){return b.key})};f.prototype.values=function(){return e(this,function(b){return b.value})};f.prototype.forEach=function(b,a){for(var e=this.entries(),c;!(c=e.next()).done;)c=c.value,b.call(a,c[1],c[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var c=function(b,c){var e;e=c&&typeof c;"object"==e||"function"==e?a.has(c)?e=a.get(c):(e=""+ ++h,a.set(c,e)):e="p_"+c;var d=b.data_[e];if(d&&$jscomp.owns(b.data_,e))for(var f=0;f<
d.length;f++){var p=d[f];if(c!==c&&p.key!==p.key||c===p.key)return{id:e,list:d,index:f,entry:p}}return{id:e,list:d,index:-1,entry:void 0}},e=function(b,c){var a=b.head_;return $jscomp.iteratorPrototype(function(){if(a){for(;a.head!=b.head_;)a=a.previous;for(;a.next!=a.head;)return a=a.next,{done:!1,value:c(a)};a=null}return{done:!0,value:void 0}})},b=function(){var b={};return b.previous=b.next=b.head=b},h=0;return f},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(d){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),c=new d($jscomp.makeIterator([a]));if(!c.has(a)||1!=c.size||c.add(a)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var e=c.entries(),b=e.next();if(b.done||b.value[0]!=a||b.value[1]!=a)return!1;b=e.next();return b.done||b.value[0]==a||4!=b.value[0].x||b.value[1]!=b.value[0]?!1:e.next().done}catch(h){return!1}}())return d;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var a=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)this.add(c.value)}this.size=this.map_.size};a.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};a.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};a.prototype.clear=function(){this.map_.clear();this.size=0};a.prototype.has=function(a){return this.map_.has(a)};a.prototype.entries=
function(){return this.map_.entries()};a.prototype.values=function(){return this.map_.values()};a.prototype[Symbol.iterator]=a.prototype.values;a.prototype.forEach=function(a,c){var e=this;this.map_.forEach(function(b){return a.call(c,b,b,e)})};return a},"es6-impl","es3");$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(d,a){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var f=0,c={next:function(){if(f<d.length){var e=f++;return{value:a(e,d[e]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
var AboutPage=function(){return{initialize:function(d){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){window.location=App.getPiecePath()})},draw:function(){},getPath:function(){return"about.html"}}}(),AdManager=function(){(function(){for(var d=document.querySelectorAll("body > div#ad > div"),a=0;a<d.length;a++)d[a].addEventListener("click",function(){window.location="https://www.facebook.com/unicef"})})()}(),AJAX=function(){return{GET:function(d,
a,f){a=void 0===a?null:a;f=void 0===f?null:f;var c=new XMLHttpRequest;c.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==a&&a(this.responseText):null!==f&&f(this.status))};c.open("GET",d,!0);c.send()}}}(),CatalogPage=function(){function d(){AJAX.GET(App.getPiecesPath()+"indexes.json",function(a){a=JSON.parse(a);var d=a.scales;1==b.length?a.hasOwnProperty(b[0])&&(d=a[b[0]]):1<b.length&&"scales"==b[0]&&a.scales.hasOwnProperty(b[1])&&(d=a.scales[b[1]]);e={query:b,tiles:[]};
a=[];for(g in d)d.hasOwnProperty(g)&&"_"!==g.substring(0,1)&&a.push(g);a.sort(function(a,b){var c=Locale.getTranslation(d[a]._desc,"en"),e=Locale.getTranslation(d[b]._desc,"en");return c<e?-1:c>e?1:0});for(var f=0;f<a.length;f++){var g=a[f],n=d[g];if("_"!==g.substring(0,1)){var g={id:g,description:n._desc},p=0;for(keyInNextLevel in n)n.hasOwnProperty(keyInNextLevel)&&"_"!==keyInNextLevel.substring(0,1)&&(p+=1);0>=p?g.type="piece":(g.type="folder",g.total=p);e.tiles.push(g)}}c()})}function a(a){a=
a.target.getAttribute("data");window.location=App.getPagePath(CatalogPage)+"?q="+encodeURIComponent("scales,"+a)}function f(a){window.location=App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a.target.getAttribute("data"))}function c(){for(var b=0;b<e.tiles.length;b++){var c=e.tiles[b];if("folder"==c.type){var d=document.createElement("div");d.classList.add("tile");d.classList.add("folder");d.setAttribute("data",c.id);d.innerHTML=Locale.getTranslation(c.description);d.addEventListener("click",
a);h.appendChild(d)}else d=document.createElement("div"),d.classList.add("tile"),d.classList.add("piece"),d.setAttribute("data",c.id),d.innerHTML=Locale.getTranslation(c.description),d.addEventListener("click",f),h.appendChild(d),c.hasOwnProperty("data")}}var e={},b="",h=null;return{initialize:function(a){h=document.querySelector("div#tiles");window.hasOwnProperty("catalogSnapshot")&&(e=window.catalogSnapshot);parseInt(a.p);b=Array.from(new Set((a.q||"").split(",")));d()},draw:function(){},getPath:function(){return"catalog.html"}}}(),
Header=function(){function d(){window.location=App.getPagePath(PDFPage)}function a(){window.location=App.getPagePath(SharePage)}function f(){window.location=App.getPagePath(CatalogPage)}function c(){window.location=App.getPagePath(AboutPage)}var e=null,b=null,h=null;return{initialize:function(){e=document.querySelector("div#header > div#controls > div.control#pdf");e.addEventListener("click",d);b=document.querySelector("div#header > div#controls > div.control#share");b.addEventListener("click",a);
h=document.querySelector("div#header > div#controls > div.control#open");h.addEventListener("click",f);document.querySelector("div#header > div#title  > div#text").addEventListener("click",c);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",c);document.querySelector("div#header > div#title  > div#text").innerHTML=Locale.getApplicationTitle()},highlight:function(a){e.classList.remove("highlighted");b.classList.remove("highlighted");h.classList.remove("highlighted");
a===PDFPage?e.classList.add("highlighted"):a===SharePage?b.classList.add("highlighted"):a===CatalogPage&&h.classList.add("highlighted")}}}(),IndexPage=function(){var d=null,a=0,f=function(){function c(b){b=b.target.id;d.getData();if("pre"===b){var c=d.getPreBar(a);b=d.getTotalVerticals()-1;null!==c&&(b=c.first);window.location=window.location.pathname+"?p="+d.getData().id+"&v="+b}else"next"===b?(c=d.getNextBar(a),b=0,null!==c&&(b=c.first),window.location=window.location.pathname+"?p="+d.getData().id+
"&v="+b):"reload"===b&&(window.location=window.location.pathname+"?p="+d.getData().id+"&v=0")}return{initialize:function(){for(var a=document.querySelectorAll("body > div#container > div#music > div#header > div#controls > div.control"),e=0;e<a.length;e++)a[e].addEventListener("click",c)},enableControls:function(){for(var a=document.querySelectorAll("body > div#container > div#music > div#header > div#controls > div.control"),c=0;c<a.length;c++)a[c].classList.remove("disabled")}}}(),c=function(){function e(a){var b=
a.clientX,c=a.clientY;"ontouchstart"in window&&(b=a.touches[0].clientX,c=a.touches[0].clientY);f(b,c)}function b(b){b=null;for(var e=document.querySelectorAll("body > div#container > div#notes > div.note"),f=0;f<e.length;f++)if(e[f].classList.contains("selected")){b=e[f];break}if(null!==b){b.classList.remove("selected");StringInstrumentSimulator.stop();var e=d.getBar(a),f=a-e.first,g=e.verticals[f],g=Array.from(g.notes.keys());"playAllNotesAndMoveNext"!==b.id&&"muteAndMoveNext"!==b.id?(g=[parseInt(b.getAttribute("value"))],
m.changeNotesColor(f,g,"green"),m.changeNotesSize(f,g,1)):(m.changeNotesColor(f,g,"black"),m.changeNotesSize(f,g,1),a+=1,b=!1,a>=e.first+e.verticals.length&&(b=!0),a>=d.getTotalVerticals()&&(a=0),b?c.firstDraw():(f+=1,g=e.verticals[f],g=Array.from(g.notes.keys()),m.changeNotesColor(f,g,"green"),m.changeNotesSize(f,g,1),l()))}}function f(b,c){for(var e=null,f=document.querySelectorAll("body > div#container > div#notes > div.note"),g=0;g<f.length;g++){var n=f[g].getBoundingClientRect();if(b>=n.left&&
b<=n.right&&c>=n.top&&c<=n.bottom){e=f[g];break}}if(null!==e){for(;!e.classList.contains("note");)e=e.parentNode;e.classList.add("selected");var g=d.getBar(a),f=a-g.first,n=g.verticals[f],h=[],k=[];if("playAllNotesAndMoveNext"===e.id)for(g=0;g<n.notes.length;g++)h.push(Note.getNoteFrequency(n.notes[g])),k.push(g);else if("muteAndMoveNext"===e.id)for(g=0;g<n.notes.length;g++)h.push(0),k.push(g);else e=parseInt(e.getAttribute("value")),h.push(Note.getNoteFrequency(n.notes[e])),k.push(e);"r"===n.duration.substr(-1)?
StringInstrumentSimulator.play([0]):StringInstrumentSimulator.play(h);m.changeNotesColor(f,k,"red");m.changeNotesSize(f,k,1.3)}}function l(){for(var b=document.querySelectorAll("body > div#container > div#notes > div.note"),c=0;c<b.length;c++)"playAllNotesAndMoveNext"!==b[c].id&&"muteAndMoveNext"!==b[c].id&&b[c].parentNode.removeChild(b[c]);var b=document.querySelector("body > div#container > div#notes"),c=d.getBar(a),e=c.verticals[a-c.first];if("r"!==e.duration.substr(-1))for(c=e.notes.length-1;0<=
c;c--){var f=document.createElement("div");f.classList.add("note");f.setAttribute("value",""+c);var h=f,k;k=Note.getNoteDetail(e.notes[c]);var l=""===k.accidental?"":"withAccidental";k=('<div class="natural YYY">'+k.natural+'</div><div class="accidental XXX"></div><div class="octave ZZZ">'+k.octave+"</div>").replace("XXX",""===k.accidental?"hidden":k.accidental).replace("YYY",l).replace("ZZZ",l);h.innerHTML=k;b.appendChild(f)}}function k(){m.display();l()}var m=null;return{initialize:function(){var a=
"mousedown",c="mouseup";"ontouchstart"in window&&(a="touchstart",c="touchend");window.addEventListener(a,e);window.addEventListener(c,b);m=new MusicPlayer(document.querySelector("body > div#container > div#music > div#sheet"))},playNoteAtPosition:f,reDraw:k,firstDraw:function(){m.setPiece(d);m.setFocus(a);k();var b=d.getBar(a),c=a-b.first;m.changeNotesColor(c,Array.from(b.verticals[c].notes.keys()),"green");document.querySelector("body > div#container > div#music > div#header > div#title").innerHTML=
Locale.getTranslation(d.getData().descriptions)}}}();return{initialize:function(e){function b(b){a>=d.getTotalVerticals()&&(a=0);c.firstDraw();f.enableControls();null!==b&&c.playNoteAtPosition(b.x,b.y);sessionStorage.lastPieceId=d.getData().id;b=d.getNextBar(a);var e=0;null!==b&&(e=b.first);AJAX.GET(window.location.pathname+"?p="+d.getData().id+"&v="+e)}var h=e.p||"default";a=parseInt(e.v)||0;var l=null;"unhandledEvent"in e&&e.lastPage===App.getPagePath(IndexPage)&&(l=e.unhandledEvent);c.initialize();
f.initialize();d=MusicStorageManager.getPiece(h);null!==d?b(l):(LoadingIconManager.show(),AJAX.GET(App.getPiecesPath()+h+".json",function(a){d=Piece.createFromString(a);MusicStorageManager.setPiece(d);b(l);LoadingIconManager.hide()},function(b){alert(Locale.getPieceLoadingFailureNotice(h));window.location=App.getPagePath(CatalogPage)}))},draw:function(){null!==d&&c.reDraw()},getPath:function(){return"index.html"}}}(),LoadingIconManager=function(){var d=0,a=document.querySelector("body > div#loading");
return{show:function(){setTimeout(function(){110<(new Date).getTime()-d&&a.classList.remove("hidden")},100)},hide:function(){a.classList.add("hidden");d=(new Date).getTime()}}}(),Locale=function(){function d(){if("language"in localStorage&&0<=c.indexOf(localStorage.language))e=localStorage.language;else{var b=navigator.languages&&navigator.languages[0]||navigator.language||navigator.userLanguage,b=b.toLowerCase();e=0<=c.indexOf(b)?b:"en"}}function a(b,a){var c;void 0===a&&(a=e);c=a in b?b[a]:b.en;
for(var d=2;d<arguments.length;d++)c=c.replace("{"+(d-1)+"}",arguments[d]);return c}function f(b,a){if(null===b)return"";var c=b.getData().descriptions,e=c.en;c.hasOwnProperty(a)&&(e=c[a]);return e}var c=["en","zh-cn"],e="en",b={en:"HeliMusic","zh-cn":"\u55e8\u4e50"},h={en:"Viola","zh-cn":"\u4e2d\u63d0\u7434"},l={en:"More resources from {1}","zh-cn":"\u66f4\u591a\u8d44\u6e90\u5728 {1}"},k={en:"Cannot load piece {1} from {2}. Please choose a new one.","zh-cn":"\u65e0\u6cd5\u4ece{2}\u4e0b\u8f7d\u66f2\u76ee{1}\u3002\u8bf7\u9009\u62e9\u65b0\u66f2\u76ee\u3002"},
m={en:"Share <b>{1}</b> to your friends using buttons above or your browser's sharing functions!","zh-cn":"\u4f7f\u7528\u4e0a\u9762\u7684\u6309\u94ae\u6216\u8005\u6d4f\u89c8\u5668\u7684\u5206\u4eab\u529f\u80fd\u628a{1}\u5206\u4eab\u7ed9\u4f60\u7684\u670b\u53cb\uff01"};d();return{checkLanguage:d,getProjectName:function(c){return a(b,c)},getApplicationTitle:function(b){return a(h,b)},getPrintFooter:function(b){return a(l,b,window.location.hostname)},getTranslation:a,getPieceLoadingFailureNotice:function(b,
c){return a(k,c,b,App.getPiecesPath())},getSharingTitle:function(b,c){return a(m,c,f(b))},getPieceDescription:f}}();
function MusicPlayer(d){function a(b){for(var a=b.first,e=[],d=0;d<b.verticals.length;d++){for(var f=[],g=0;g<b.verticals[d].notes.length;g++)f.push({color:"black",size:"1.0"});e.push(f)}return{isOnBar:function(b){return a===b.first},changeNotesSize:function(b,a,c){for(var d=0;d<a.length;d++)e[b][a[d]].size=c},changeNotesColor:function(b,a,c){for(var d=0;d<a.length;d++)e[b][a[d]].color=c},drawAllOrnaments:function(){for(var b=0<=navigator.userAgent.toLowerCase().indexOf("firefox"),a=0;a<e.length;a++)for(var d=
0;d<e[a].length;d++){if("1.0"!==e[a][d].size&&!b){var f=c(a,[d]);f[0].style.transformOrigin="50% 50%";f[0].style.transform="scale("+e[a][d].size+")"}"black"!==e[a][d].color&&(f=c(a,[d]),f[0].setAttribute("fill",e[a][d].color))}}}}function f(){b.innerHTML="";var a=new Vex.Flow.Renderer(b,Vex.Flow.Renderer.Backends.SVG);context=a.getContext();a.resize(b.clientWidth,b.clientHeight);context.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return context}function c(b,a){for(var c=document.querySelectorAll("#vf-"+
l[b].attrs.id+" g.vf-notehead path"),e=[],d=0;d<a.length;d++)e.push(c[a[d]]);return e}function e(b){var a=h.getBar(b);return b-a.first}var b=d,h=null,l=[],k=0,m=null;return{setPiece:function(b){h=b;k=0},setFocus:function(b){k=b},display:function(){var b=f(),c=new Vex.Flow.Stave(4,64,b.width-8),e=h.getBar(k);c.addClef(e.clef).addTimeSignature(e.time).addKeySignature(VFUtility.toVFKeySignature(e.key));c.setMeasure(h.getData().bars.indexOf(e)+1);c.setContext(b).draw();l=[];for(var d={},z=0;z<e.verticals.length;z++)l.push(VFUtility.prepareStaveNote(e.key,
e.clef,e.verticals[z],d));d=Vex.Flow.Beam.generateBeams(l);Vex.Flow.Formatter.FormatAndDraw(b,c,l);d.forEach(function(a){a.setContext(b).draw()});null!==m&&m.isOnBar(e)?m.drawAllOrnaments():m=new a(e)},changeNotesSize:function(b,a,d){d=void 0===d?"1.0":d;if(!(0<=navigator.userAgent.toLowerCase().indexOf("firefox"))){b=e(b);for(var f=c(b,a),g=0;g<f.length;g++)f[g].style.transformOrigin="50% 50%",f[g].style.transform="scale("+d+")";m.changeNotesSize(b,a,d)}},changeNotesColor:function(b,a,d){d=void 0===
d?"black":d;b=e(b);for(var f=c(b,a),g=0;g<f.length;g++)f[g].setAttribute("fill",d);m.changeNotesColor(b,a,d)}}}var MusicStorageManager=function(){return{getPiece:function(d){"default"===d&&(d=Locale.getApplicationTitle("en")+d);d=localStorage.getItem("_piece_"+d);return null===d?null:Piece.createFromString(d)},setPiece:function(d){d=d.getData();var a="_piece_"+d.id;"default"===d.id&&(a="_piece_"+Locale.getApplicationTitle("en")+d.id);localStorage.setItem(a,JSON.stringify(d))}}}();
function MusicViewer(d){function a(){e.innerHTML="";var b=Vex.Flow.Renderer.Backends.SVG;"CANVAS"===e.tagName.toUpperCase()&&(b=Vex.Flow.Renderer.Backends.CANVAS);b=new Vex.Flow.Renderer(e,b);k=b.getContext();b.resize(e.clientWidth,e.clientHeight);k.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return k}function f(a,c,d){c=void 0===c?0:c;d=void 0===d?0:d;var f={"C\u266f":7,"b\u266d":5,"E\u266d":3,"c\u266f":4,d:1,c:3,"a\u266f":7,F:1,B:5,D:2,"G\u266d":6,"B\u266d":2,"g\u266f":5,e:1,"C\u266d":7,
"F\u266f":6,b:2,G:1,"a\u266d":7,E:4,a:0,C:0,"A\u266d":4,"f\u266f":3,"d\u266f":6,g:2,A:3,f:4,"D\u266d":5,"e\u266d":6};c=(0===c?e.clientWidth:c)-8;var g=0===d?e.clientHeight:d;d=Math.floor(g/160);for(var g=40+.33*(g-160*d),h=b.getData(),k=[],n=0;n<d;n++)k.push({height:160,staves:[]});for(n=0;n<d&&a<h.bars.length;n++){for(var m=[],p="",u="",x="",q=a;q<h.bars.length;q++){var v=h.bars[q],r={clef:"",key:"",time:"",verticals:v.verticals.length,size:0};v.clef!==p&&(p=r.clef=v.clef,r.size+=25);v.key!==u&&
(u=r.key=v.key,r.size+=8*f[v.key]);v.time!==x&&(x=r.time=v.time,r.size+=14);r.size+=50*r.verticals;m.push(r)}u=0;p=h.bars.length-a;for(q=a;q<h.bars.length;q++)if(u+=m[q-a].size,u>c){p=q>a?q-a:1;break}for(q=u=0;q<p;q++)u+=m[q].size;for(q=x=0;q<p;q++)l=v=q+a,r=m[q].size/u*c,k[n].staves.push({barIndex:v,left:x+4,width:r}),x+=r;a+=p}return{rows:k,staveOffsetTop:g}}function c(a){var c=b.getData();a=0==a?c.bars.length-1:a-1;for(var e=0,d=0;d<c.bars.length;d++){for(var h=e,g=f(e),k=0;k<g.rows.length;k++)for(var l=
0;l<g.rows[k].length;l++){if(a===g.rows[k][l].barIndex)return 0==k+l?h:e;e=g.rows[k][l].barIndex}e+=1}}var e=d,b=null,h=0,l=0,k=null,m=null;a();return{setPiece:function(a){b=a},setFirstBar:function(b){h=b},display:function(){a();var c=b.getData(),e=f(h),d=e.staveOffsetTop;m=e;for(var l=0;l<e.rows.length;l++){for(var z="",B="",C="",w=0;w<e.rows[l].staves.length;w++){var t=c.bars[e.rows[l].staves[w].barIndex],A=new Vex.Flow.Stave(e.rows[l].staves[w].left,d,e.rows[l].staves[w].width);0==w&&A.setMeasure(e.rows[l].staves[w].barIndex+
1);t.clef!==z&&(z=t.clef,A.addClef(t.clef));t.key!==B&&(B=t.key,A.addKeySignature(VFUtility.toVFKeySignature(t.key)));t.time!==C&&(C=t.time,A.addTimeSignature(t.time));A.setContext(k).draw();for(var u=[],x={},q=0;q<t.verticals.length;q++)u.push(VFUtility.prepareStaveNote(t.key,t.clef,t.verticals[q],x));t=Vex.Flow.Beam.generateBeams(u);Vex.Flow.Formatter.FormatAndDraw(k,A,u);t.forEach(function(b){b.setContext(k).draw()})}d+=e.rows[l].height}},getLastBar:function(){return l},getCurrentLayout:function(){return m},
getFirstBarInPreviousPage:c,getFirstBarInLastPage:function(){return c(0)}}}
var Note=function(){function d(c){var b={A:[0,1],"B\ud834\udd2b":[0,1],"G\ud834\udd2a":[0,1],"A\u266f":[0,2],"B\u266d":[0,2],B:[0,3],"A\ud834\udd2a":[0,3],"C\u266d":[1,3],C:[1,4],"D\ud834\udd2b":[1,4],"B\u266f":[0,4],"C\u266f":[1,5],"D\u266d":[1,5],D:[1,6],"E\ud834\udd2b":[1,6],"C\ud834\udd2a":[1,6],"D\u266f":[1,7],"E\u266d":[1,7],"F\ud834\udd2b":[1,7],E:[1,8],"F\u266d":[1,8],"D\ud834\udd2a":[1,8],F:[1,9],"G\ud834\udd2b":[1,9],"E\u266f":[1,9],"F\u266f":[1,10],"G\u266d":[1,10],G:[1,11],"A\ud834\udd2b":[1,
11],"F\ud834\udd2a":[1,11],"G\u266f":[1,12],"A\u266d":[1,12]};c=a(c);var e=c.natural+c.accidental;return b.hasOwnProperty(e)?(b=b[e],b[1]+12*(c.octave-b[0])):-1}function a(a){var b={natural:"",octave:-1,accidental:""};if(0>=a.length)return b;b.natural=a[0];b.octave=parseInt(a.substring(a.length-1,a.length));b.accidental="";b.accidentalASCII="";2<a.length&&(1==a.indexOf("\u266d")?(b.accidental="\u266d",b.accidentalASCII="b"):1==a.indexOf("\u266f")?(b.accidental="\u266f",b.accidentalASCII="#"):1==a.indexOf("\ud834\udd2b")?
(b.accidental="\ud834\udd2b",b.accidentalASCII="bb"):1==a.indexOf("\ud834\udd2a")&&(b.accidental="\ud834\udd2a",b.accidentalASCII="##"));return b}function f(a,b){var e=c[a],d="";"\u266d"==e.sharpflat&&"BEADGCF".indexOf(b)<e.amount?d="\u266d":"\u266f"==e.sharpflat&&"FCGDAEB".indexOf(b)<e.amount&&(d="\u266f");return d}var c={"D\u266d":{index:0,sharpflat:"\u266d",amount:5},"G\u266f":{index:1,sharpflat:"\u266f",amount:8},"b\u266d":{index:2,sharpflat:"\u266d",amount:5},"C\u266d":{index:3,sharpflat:"\u266d",
amount:7},e:{index:4,sharpflat:"\u266f",amount:1},"C\u266f":{index:5,sharpflat:"\u266f",amount:7},B:{index:6,sharpflat:"\u266f",amount:5},g:{index:7,sharpflat:"\u266d",amount:2},f:{index:8,sharpflat:"\u266d",amount:4},"F\u266d":{index:9,sharpflat:"\u266d",amount:8},a:{index:10,sharpflat:"\u266f",amount:0},G:{index:11,sharpflat:"\u266f",amount:1},"B\u266d":{index:12,sharpflat:"\u266d",amount:2},"e\u266f":{index:13,sharpflat:"\u266f",amount:8},"a\u266f":{index:14,sharpflat:"\u266f",amount:7},"d\u266d":{index:15,
sharpflat:"\u266d",amount:8},d:{index:16,sharpflat:"\u266d",amount:1},"F\u266f":{index:17,sharpflat:"\u266f",amount:6},"g\u266f":{index:18,sharpflat:"\u266f",amount:5},C:{index:19,sharpflat:"\u266f",amount:0},D:{index:20,sharpflat:"\u266f",amount:2},"A\u266d":{index:21,sharpflat:"\u266d",amount:4},A:{index:22,sharpflat:"\u266f",amount:3},"E\u266d":{index:23,sharpflat:"\u266d",amount:3},"f\u266f":{index:24,sharpflat:"\u266f",amount:3},c:{index:25,sharpflat:"\u266d",amount:3},b:{index:26,sharpflat:"\u266f",
amount:2},F:{index:27,sharpflat:"\u266d",amount:1},E:{index:28,sharpflat:"\u266f",amount:4},"G\u266d":{index:29,sharpflat:"\u266d",amount:6},"c\u266f":{index:30,sharpflat:"\u266f",amount:4},"e\u266d":{index:31,sharpflat:"\u266d",amount:6},"a\u266d":{index:32,sharpflat:"\u266d",amount:7},"d\u266f":{index:33,sharpflat:"\u266f",amount:6}};return{flat:"\u266d",sharp:"\u266f",flatflat:"\ud834\udd2b",sharpsharp:"\ud834\udd2a",getNoteOrder:d,getNoteFrequency:function(a){a=d(a);"DoubleBass"===Locale.getApplicationTitle("en")&&
(a-=12);return 0>a?0:440*Math.pow(Math.pow(2,1/12),a-49)},getNoteDetail:a,getDefaultAccidental:f,getDefaultAccidentalASCII:function(a,b){return f(a,b).replace("\u266f","#").replace("\u266d","b")},getFirstNoteInKey:function(a){a=a.substring(0,1);return 0<="GAB".indexOf(a)?a+"3":a+"4"}}}(),PDFConverter=function(d,a){function f(){var a=c.querySelectorAll("div.page");h+=1;h>=a.length?e(b):(b.addPage(),b.addHTML(a[h],f))}var c=d,e=a,b=null,h=0;return{convert:function(){var a=c.querySelectorAll("div.page");
0>=a.length?e(null):(b=new jsPDF("p","pt","a4"),h=0,b.addHTML(a[0],f))}}},PDFPage=function(){function d(){LoadingIconManager.show();var a=document.querySelector("body > div#pdfRenderer");a.style.display="block";var c=new PDFRenderer(a),d=MusicStorageManager.getPiece(App.getDefaultPieceId());null===d?alert("Cannot show PDF"):(c.render(d),(new PDFConverter(a,function(b){a.style.display="none";window.top.pdfdata=b.output("arraybuffer");document.querySelector("body > div#container > div#wrapper").innerHTML=
'<embed src="/pdf.js/viewer.html">'})).convert(d))}var a=function(){return{onComplete:function(){LoadingIconManager.hide()},onerror:onerror}}();return{initialize:function(f){window.top.PDFJS=a;LoadingIconManager.show();document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){window.location=App.getPiecePath()});d();f=App.getPiecePath();history.replaceState("","",f)},draw:function(){},getPath:function(){return"pdf.html"}}}(),PDFRenderer=function(d){return{render:function(a){d.innerHTML=
"";for(var f=-1,c=-1,e=0;8>e;e++){c+=1;f+=1;if(f>=a.getData().bars.length)break;var b;b=c;var h=document.createElement("div");h.classList.add("page");h.innerHTML='<div class="header"></div><div class="title XXX"></div><canvas class="music"></canvas><div class="footer"></div>'.replace("XXX",0===b?"":"hide");d.appendChild(h);b=h;b.querySelector("div.title").innerHTML=Locale.getTranslation(a.getData().descriptions);b.querySelector("div.footer").innerHTML=Locale.getPrintFooter();b=new MusicViewer(b.querySelector("canvas.music"));
b.setPiece(a);b.setFirstBar(f);b.display();f=b.getLastBar()}}}},Piece=function(){function d(a){function d(a){for(var b=0;b<c.bars.length;b++)if(c.bars[b].first<=a&&a<c.bars[b].first+c.bars[b].verticals.length)return c.bars[b];return null}var c=JSON.parse(a);return{getData:function(){return c},getBar:d,getPreBar:function(a){a=d(a);return null===a?null:d(a.first-1)},getNextBar:function(a){a=d(a);return null===a?null:d(a.first+a.verticals.length)},getTotalVerticals:function(){var a=c.bars[c.bars.length-
1];return a.first+a.verticals.length}}}return{createFromString:function(a){return new d(a)}}}(),SharePage=function(){function d(c){var d=c.target.id;d in f?(c=f[d].replace("URL",encodeURIComponent(a.url)).replace("DESCRIPTION",encodeURIComponent(a.description)).replace("VIA","Metronome"),window.open(c,"_blank")):"mail"==d?(c="mailto:?subject="+encodeURIComponent(a.description)+"&body="+encodeURIComponent(a.url),window.open(c,"_blank")):"link"==c.target.id&&(c=document.querySelector("body > input#copy"),
c.classList.remove("hidden"),c.value=a.url,c.select(),document.execCommand("copy"),c.classList.add("hidden"));window.location=App.getPiecePath()}var a={url:"",description:""},f={qq:"http://v.t.qq.com/share/share.php?url=URL&title=DESCRIPTION",weibo:"http://service.weibo.com/share/share.php?url=URL&title=DESCRIPTION",qzone:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=URL&title=DESCRIPTION",facebook:"https://www.facebook.com/sharer/sharer.php?u=URL&t=DESCRIPTION",twitter:"https://twitter.com/intent/tweet?text=DESCRIPTION&url=URL&via=VIA"};
return{initialize:function(c){c=App.getDefaultPieceId();var e=MusicStorageManager.getPiece(c);document.querySelector("body > div#container > div#share > div#title").innerHTML=Locale.getSharingTitle(e);e=App.getHost()+App.getPiecePath();history.replaceState("","",e);a.url=e;e=MusicStorageManager.getPiece(c);a.description=Locale.getPieceDescription(e)+", "+Locale.getApplicationTitle()+", "+Locale.getProjectName();c=document.querySelectorAll("body > div#container > div#share > div#services > div.service");
for(e=0;e<c.length;e++)c[e].addEventListener("click",d);document.querySelector("body > div#container > div#controls > div#ok").addEventListener("click",function(){window.location=App.getPiecePath()})},draw:function(){},getPath:function(){return"share.html"}}}(),StringInstrumentSimulator=function(){function d(){if(null!=a)return!0;if("AudioContext"in window)a=new AudioContext;else if("webkitAudioContext"in window)a=new webkitAudioContext;else return a=null,!1;f=a.createGain();f.gain.value=0;f.connect(a.destination);
return!0}var a=null,f=null,c=[];return{play:function(e){d();for(var b=0;b<e.length;b++)if(!(0>=e[b])){var h=a.createOscillator();h.frequency.value=e[b];var l=h,k=Math.PI,m=new Float32Array(12),g=new Float32Array(12),n=[.49,.995,.94,.425,.48,0,.365,.04,.085,0,.09,0],k=[0,0,k/2,0,k/2,0,k/2,0,k/2,0,k/2,0];m[0]=0;g[0]=0;for(var p=1;12>p;p++)m[p]=n[p]*n[0]*Math.cos(k[p]),g[p]=n[p]*n[0]*Math.sin(k[p]);m=a.createPeriodicWave(g,m);l.setPeriodicWave(m);h.connect(f);h.start(0);c.push(h)}f.gain.linearRampToValueAtTime(0,
a.currentTime);f.gain.linearRampToValueAtTime(.5,a.currentTime+.05)},stop:function(){d();f.gain.linearRampToValueAtTime(.5,a.currentTime);f.gain.linearRampToValueAtTime(0,a.currentTime+.05);setTimeout(function(){for(var a=0;a<c.length;a++){var b=c[a];b.stop(0);b.disconnect(f)}c=[]},50)},playAndStop:function(a,b,c){}}}(),VFUtility=function(){function d(a){a=Note.getNoteDetail(a);return a.natural+a.accidentalASCII+"/"+a.octave}return{toVFKeySignature:function(a){a!==a.toUpperCase()&&(a=a.toUpperCase()+
"m");return a=a.replace(Note.flat,"b").replace(Note.sharp,"#")},prepareStaveNote:function(a,f,c,e){for(var b,h,l,k=[],m=0;m<c.notes.length;m++)k.push(d(c.notes[m]));f=new Vex.Flow.StaveNote({clef:f,keys:k,duration:c.duration});if("r"!==c.duration.substr(-1))for(m=0;m<c.notes.length;m++)a:{var g=a,k=f,n=m,p=e;l=k.keys[n];var y=l.indexOf("/");b=l.substring(0,1);h=parseInt(l.substring(y+1));l=l.substring(1,y);y=b+h;h=!1;if(p.hasOwnProperty(y))if(p[y]==l)break a;else h=!0;p[y]=l;"bb"==l?k.addAccidental(n,
new Vex.Flow.Accidental("bb")):"##"==l?k.addAccidental(n,new Vex.Flow.Accidental("##")):(b=Note.getDefaultAccidentalASCII(g,b),"#"==b?"#"==l?h&&k.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==l?k.addAccidental(n,new Vex.Flow.Accidental("b")):k.addAccidental(n,new Vex.Flow.Accidental("n")):"b"==b?"#"==l?k.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==l?h&&k.addAccidental(n,new Vex.Flow.Accidental("b")):k.addAccidental(n,new Vex.Flow.Accidental("n")):"#"==l?k.addAccidental(n,new Vex.Flow.Accidental("#")):
"b"==l?k.addAccidental(n,new Vex.Flow.Accidental("b")):h&&k.addAccidental(n,new Vex.Flow.Accidental("n")))}a=c.duration;"dd"==a.substring(a.length-2)?f.addDotToAll().addDotToAll():(c=c.duration,"d"==c.substring(c.length-1)&&f.addDotToAll());return f}}}(),App=function(){function d(){f.draw()}var a={},f=null;return{initialize:function(c){c=void 0===c?{}:c;Header.initialize();for(var e=window.location.pathname,b=window.location.search,b=("?"===b[0]?b.substr(1):b).split("&"),h=0;h<b.length;h++){var l=
b[h].split("=");c[decodeURIComponent(l[0])]=decodeURIComponent(l[1]||"")}c.lastPage=sessionStorage.lastPage||null;a=c;f=0===e.indexOf("/va/"+CatalogPage.getPath())?CatalogPage:0===e.indexOf("/va/"+AboutPage.getPath())?AboutPage:0===e.indexOf("/va/"+PDFPage.getPath())?PDFPage:0===e.indexOf("/va/"+SharePage.getPath())?SharePage:IndexPage;Header.highlight(f);f.initialize(c);sessionStorage.setItem("lastPage","/va/"+f.getPath());window.addEventListener("resize",d)},getParams:function(){return a},resize:d,
getHost:function(){var a=window.location.href;return a.substring(0,a.indexOf("/",8))},getPagePath:function(a){return"/va/"+(void 0===a?null:a).getPath()},getPiecePath:function(a){a=void 0===a?null:a;a=null===a?App.getDefaultPieceId():a.getData().id;return App.getPagePath(IndexPage)+"?p="+a},getPiecesPath:function(){return"/va/pieces/"},getDefaultPieceId:function(){var c=a,d="default";c.hasOwnProperty("p")?d=c.p:"lastPieceId"in sessionStorage&&(d=sessionStorage.lastPieceId);return d}}}();
