var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(d,c,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");d!=Array.prototype&&d!=Object.prototype&&(d[c]=f.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var c=0;return $jscomp.iteratorPrototype(function(){return c<d.length?{done:!1,value:d[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.polyfill=function(d,c,f,b){if(c){f=$jscomp.global;d=d.split(".");for(b=0;b<d.length-1;b++){var e=d[b];e in f||(f[e]={});f=f[e]}d=d[d.length-1];b=f[d];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(f,d,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.from",function(d){return d?d:function(c,d,b){$jscomp.initSymbolIterator();d=null!=d?d:function(a){return a};var e=[],a=c[Symbol.iterator];if("function"==typeof a)for(c=a.call(c);!(a=c.next()).done;)e.push(d.call(b,a.value));else for(var a=c.length,f=0;f<a;f++)e.push(d.call(b,c[f]));return e}},"es6-impl","es3");$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();var c=d[Symbol.iterator];return c?c.call(d):$jscomp.arrayIterator(d)};
$jscomp.owns=function(d,c){return Object.prototype.hasOwnProperty.call(d,c)};
$jscomp.polyfill("WeakMap",function(d){function c(a){$jscomp.owns(a,b)||$jscomp.defineProperty(a,b,{value:{}})}function f(a){var b=Object[a];b&&(Object[a]=function(a){c(a);return b(a)})}if(function(){if(!d||!Object.seal)return!1;try{var a=Object.seal({}),b=Object.seal({}),e=new d([[a,2],[b,3]]);if(2!=e.get(a)||3!=e.get(b))return!1;e["delete"](a);e.set(b,4);return!e.has(a)&&4==e.get(b)}catch(m){return!1}}())return d;var b="$jscomp_hidden_"+Math.random().toString().substring(2);f("freeze");f("preventExtensions");
f("seal");var e=0,a=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};a.prototype.set=function(a,e){c(a);if(!$jscomp.owns(a,b))throw Error("WeakMap key fail: "+a);a[b][this.id_]=e;return this};a.prototype.get=function(a){return $jscomp.owns(a,b)?a[b][this.id_]:void 0};a.prototype.has=function(a){return $jscomp.owns(a,b)&&$jscomp.owns(a[b],this.id_)};a.prototype["delete"]=
function(a){return $jscomp.owns(a,b)&&$jscomp.owns(a[b],this.id_)?delete a[b][this.id_]:!1};return a},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(d){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new d($jscomp.makeIterator([[a,"s"]]));if("s"!=b.get(a)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var e=b.entries(),g=e.next();if(g.done||g.value[0]!=a||"s"!=g.value[1])return!1;g=e.next();return g.done||4!=g.value[0].x||"t"!=g.value[1]||!e.next().done?!1:!0}catch(n){return!1}}())return d;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var c=new WeakMap,f=function(b){this.data_={};this.head_=a();this.size=0;if(b){b=$jscomp.makeIterator(b);for(var e;!(e=b.next()).done;)e=e.value,this.set(e[0],e[1])}};f.prototype.set=function(a,e){var c=b(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=e:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:e},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};f.prototype["delete"]=
function(a){a=b(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=a();this.size=0};f.prototype.has=function(a){return!!b(this,a).entry};f.prototype.get=function(a){return(a=b(this,a).entry)&&a.value};f.prototype.entries=function(){return e(this,function(a){return[a.key,
a.value]})};f.prototype.keys=function(){return e(this,function(a){return a.key})};f.prototype.values=function(){return e(this,function(a){return a.value})};f.prototype.forEach=function(a,b){for(var e=this.entries(),c;!(c=e.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var b=function(a,b){var e;e=b&&typeof b;"object"==e||"function"==e?c.has(b)?e=c.get(b):(e=""+ ++h,c.set(b,e)):e="p_"+b;var g=a.data_[e];if(g&&$jscomp.owns(a.data_,e))for(var d=0;d<
g.length;d++){var f=g[d];if(b!==b&&f.key!==f.key||b===f.key)return{id:e,list:g,index:d,entry:f}}return{id:e,list:g,index:-1,entry:void 0}},e=function(a,b){var e=a.head_;return $jscomp.iteratorPrototype(function(){if(e){for(;e.head!=a.head_;)e=e.previous;for(;e.next!=e.head;)return e=e.next,{done:!1,value:b(e)};e=null}return{done:!0,value:void 0}})},a=function(){var a={};return a.previous=a.next=a.head=a},h=0;return f},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(d){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new d($jscomp.makeIterator([c]));if(!b.has(c)||1!=b.size||b.add(c)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var e=b.entries(),a=e.next();if(a.done||a.value[0]!=c||a.value[1]!=c)return!1;a=e.next();return a.done||a.value[0]==c||4!=a.value[0].x||a.value[1]!=a.value[0]?!1:e.next().done}catch(h){return!1}}())return d;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=function(c){this.map_=new Map;if(c){c=$jscomp.makeIterator(c);for(var b;!(b=c.next()).done;)this.add(b.value)}this.size=this.map_.size};c.prototype.add=function(c){this.map_.set(c,c);this.size=this.map_.size;return this};c.prototype["delete"]=function(c){c=this.map_["delete"](c);this.size=this.map_.size;return c};c.prototype.clear=function(){this.map_.clear();this.size=0};c.prototype.has=function(c){return this.map_.has(c)};c.prototype.entries=
function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(c,b){var e=this;this.map_.forEach(function(a){return c.call(b,a,a,e)})};return c},"es6-impl","es3");$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(d,c){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var f=0,b={next:function(){if(f<d.length){var e=f++;return{value:c(e,d[e]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6-impl","es3");
var AboutPage=function(){return{initialize:function(d){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){window.location=App.getPiecePath()})},draw:function(){},getPath:function(){return"about.html"}}}(),AJAX=function(){return{GET:function(d,c,f){c=void 0===c?null:c;f=void 0===f?null:f;var b=new XMLHttpRequest;b.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==c&&c(this.responseText):null!==f&&f(this.status))};
b.open("GET",d,!0);b.send()}}}(),CatalogPage=function(){function d(){AJAX.GET(App.getPiecesPath()+"indexes.json",function(c){c=JSON.parse(c);var d=c.scales;1==a.length?c.hasOwnProperty(a[0])&&(d=c[a[0]]):1<a.length&&"scales"==a[0]&&c.scales.hasOwnProperty(a[1])&&(d=c.scales[a[1]]);e={query:a,tiles:[]};c=[];for(g in d)d.hasOwnProperty(g)&&"_"!==g.substring(0,1)&&c.push(g);c.sort(function(a,c){var e=Locale.getTranslation(d[a]._desc,"en"),b=Locale.getTranslation(d[c]._desc,"en");return e<b?-1:e>b?1:
0});for(var f=0;f<c.length;f++){var g=c[f],n=d[g];if("_"!==g.substring(0,1)){var g={id:g,description:n._desc},p=0;for(keyInNextLevel in n)n.hasOwnProperty(keyInNextLevel)&&"_"!==keyInNextLevel.substring(0,1)&&(p+=1);0>=p?g.type="piece":(g.type="folder",g.total=p);e.tiles.push(g)}}b()})}function c(a){a=a.target.getAttribute("data");window.location=App.getPagePath(CatalogPage)+"?q="+encodeURIComponent("scales,"+a)}function f(a){window.location=App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a.target.getAttribute("data"))}
function b(){for(var a=0;a<e.tiles.length;a++){var b=e.tiles[a];if("folder"==b.type){var d=document.createElement("div");d.classList.add("tile");d.classList.add("folder");d.setAttribute("data",b.id);d.innerHTML=Locale.getTranslation(b.description);d.addEventListener("click",c);h.appendChild(d)}else d=document.createElement("div"),d.classList.add("tile"),d.classList.add("piece"),d.setAttribute("data",b.id),d.innerHTML=Locale.getTranslation(b.description),d.addEventListener("click",f),h.appendChild(d),
b.hasOwnProperty("data")}}var e={},a="",h=null;return{initialize:function(b){h=document.querySelector("div#tiles");window.hasOwnProperty("catalogSnapshot")&&(e=window.catalogSnapshot);parseInt(b.p);a=Array.from(new Set((b.q||"").split(",")));d()},draw:function(){},getPath:function(){return"catalog.html"}}}(),Header=function(){function d(){window.location=App.getPagePath(PDFPage)}function c(){window.location=App.getPagePath(SharePage)}function f(){window.location=App.getPagePath(CatalogPage)}function b(){window.location=
App.getPagePath(AboutPage)}var e=null,a=null,h=null;return{initialize:function(){e=document.querySelector("div#header > div#controls > div.control#pdf");e.addEventListener("click",d);a=document.querySelector("div#header > div#controls > div.control#share");a.addEventListener("click",c);h=document.querySelector("div#header > div#controls > div.control#open");h.addEventListener("click",f);document.querySelector("div#header > div#title  > div#text").addEventListener("click",b);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",
b);document.querySelector("div#header > div#title  > div#text").innerHTML=Locale.getApplicationTitle()},highlight:function(b){e.classList.remove("highlighted");a.classList.remove("highlighted");h.classList.remove("highlighted");b===PDFPage?e.classList.add("highlighted"):b===SharePage?a.classList.add("highlighted"):b===CatalogPage&&h.classList.add("highlighted")}}}(),IndexPage=function(){var d=null,c=0,f=function(){function b(a){a=a.target.id;d.getData();if("pre"===a){var b=d.getPreBar(c);a=d.getTotalVerticals()-
1;null!==b&&(a=b.first);window.location=window.location.pathname+"?p="+d.getData().id+"&v="+a}else"next"===a?(b=d.getNextBar(c),a=0,null!==b&&(a=b.first),window.location=window.location.pathname+"?p="+d.getData().id+"&v="+a):"reload"===a&&(window.location=window.location.pathname+"?p="+d.getData().id+"&v=0")}return{initialize:function(){for(var a=document.querySelectorAll("body > div#container > div#music > div#header > div#controls > div.control"),c=0;c<a.length;c++)a[c].addEventListener("click",
b)},enableControls:function(){for(var a=document.querySelectorAll("body > div#container > div#music > div#header > div#controls > div.control"),b=0;b<a.length;b++)a[b].classList.remove("disabled")}}}(),b=function(){function e(a){var b=a.clientX,c=a.clientY;"ontouchstart"in window&&(b=a.touches[0].clientX,c=a.touches[0].clientY);f(b,c)}function a(a){a=null;for(var e=document.querySelectorAll("body > div#container > div#notes > div.note"),g=0;g<e.length;g++)if(e[g].classList.contains("selected")){a=
e[g];break}if(null!==a){a.classList.remove("selected");StringInstrumentSimulator.stop();var e=d.getBar(c),g=c-e.first,f=e.verticals[g],f=Array.from(f.notes.keys());"playAllNotesAndMoveNext"!==a.id&&"muteAndMoveNext"!==a.id?(f=[parseInt(a.getAttribute("value"))],m.changeNotesColor(g,f,"green"),m.changeNotesSize(g,f,1)):(m.changeNotesColor(g,f,"black"),m.changeNotesSize(g,f,1),c+=1,a=!1,c>=e.first+e.verticals.length&&(a=!0),c>=d.getTotalVerticals()&&(c=0),a?b.firstDraw():(g+=1,f=e.verticals[g],f=Array.from(f.notes.keys()),
m.changeNotesColor(g,f,"green"),m.changeNotesSize(g,f,1),l()))}}function f(a,b){for(var e=null,g=document.querySelectorAll("body > div#container > div#notes > div.note"),f=0;f<g.length;f++){var n=g[f].getBoundingClientRect();if(a>=n.left&&a<=n.right&&b>=n.top&&b<=n.bottom){e=g[f];break}}if(null!==e){for(;!e.classList.contains("note");)e=e.parentNode;e.classList.add("selected");var f=d.getBar(c),g=c-f.first,n=f.verticals[g],h=[],k=[];if("playAllNotesAndMoveNext"===e.id)for(f=0;f<n.notes.length;f++)h.push(Note.getNoteFrequency(n.notes[f])),
k.push(f);else if("muteAndMoveNext"===e.id)for(f=0;f<n.notes.length;f++)h.push(0),k.push(f);else e=parseInt(e.getAttribute("value")),h.push(Note.getNoteFrequency(n.notes[e])),k.push(e);"r"===n.duration.substr(-1)?StringInstrumentSimulator.play([0]):StringInstrumentSimulator.play(h);m.changeNotesColor(g,k,"red");m.changeNotesSize(g,k,1.3)}}function l(){for(var a=document.querySelectorAll("body > div#container > div#notes > div.note"),b=0;b<a.length;b++)"playAllNotesAndMoveNext"!==a[b].id&&"muteAndMoveNext"!==
a[b].id&&a[b].parentNode.removeChild(a[b]);var a=document.querySelector("body > div#container > div#notes"),b=d.getBar(c),e=b.verticals[c-b.first];if("r"!==e.duration.substr(-1))for(b=e.notes.length-1;0<=b;b--){var f=document.createElement("div");f.classList.add("note");f.setAttribute("value",""+b);var h=f,k;k=Note.getNoteDetail(e.notes[b]);var l=""===k.accidental?"":"withAccidental";k=('<div class="natural YYY">'+k.natural+'</div><div class="accidental XXX"></div><div class="octave ZZZ">'+k.octave+
"</div>").replace("XXX",""===k.accidental?"hidden":k.accidental).replace("YYY",l).replace("ZZZ",l);h.innerHTML=k;a.appendChild(f)}}function k(){m.display();l()}var m=null;return{initialize:function(){var b="mousedown",c="mouseup";"ontouchstart"in window&&(b="touchstart",c="touchend");window.addEventListener(b,e);window.addEventListener(c,a);m=new MusicPlayer(document.querySelector("body > div#container > div#music > div#sheet"))},playNoteAtPosition:f,reDraw:k,firstDraw:function(){m.setPiece(d);m.setFocus(c);
k();var a=d.getBar(c),b=c-a.first;m.changeNotesColor(b,Array.from(a.verticals[b].notes.keys()),"green");document.querySelector("body > div#container > div#music > div#header > div#title").innerHTML=Locale.getTranslation(d.getData().descriptions)}}}();return{initialize:function(e){function a(a){c>=d.getTotalVerticals()&&(c=0);b.firstDraw();f.enableControls();null!==a&&b.playNoteAtPosition(a.x,a.y);sessionStorage.lastPieceId=d.getData().id;a=d.getNextBar(c);var e=0;null!==a&&(e=a.first);AJAX.GET(window.location.pathname+
"?p="+d.getData().id+"&v="+e)}var h=e.p||"default";c=parseInt(e.v)||0;var l=null;"unhandledEvent"in e&&e.lastPage===App.getPagePath(IndexPage)&&(l=e.unhandledEvent);b.initialize();f.initialize();d=MusicStorageManager.getPiece(h);null!==d?a(l):(LoadingIconManager.show(),AJAX.GET(App.getPiecesPath()+h+".json",function(b){d=Piece.createFromString(b);MusicStorageManager.setPiece(d);a(l);LoadingIconManager.hide()},function(a){alert(Locale.getPieceLoadingFailureNotice(h));window.location=App.getPagePath(CatalogPage)}))},
draw:function(){null!==d&&b.reDraw()},getPath:function(){return"index.html"}}}(),LoadingIconManager=function(){var d=0,c=document.querySelector("body > div#loading");return{show:function(){setTimeout(function(){110<(new Date).getTime()-d&&c.classList.remove("hidden")},100)},hide:function(){c.classList.add("hidden");d=(new Date).getTime()}}}(),Locale=function(){function d(){if("language"in localStorage&&0<=b.indexOf(localStorage.language))e=localStorage.language;else{var a=navigator.languages&&navigator.languages[0]||
navigator.language||navigator.userLanguage,a=a.toLowerCase();e=0<=b.indexOf(a)?a:"en"}}function c(a,b){var c;void 0===b&&(b=e);c=b in a?a[b]:a.en;for(var d=2;d<arguments.length;d++)c=c.replace("{"+(d-1)+"}",arguments[d]);return c}function f(a,b){if(null===a)return"";var e=a.getData().descriptions,c=e.en;e.hasOwnProperty(b)&&(c=e[b]);return c}var b=["en","zh-cn"],e="en",a={en:"HeliMusic","zh-cn":"\u55e8\u4e50"},h={en:"Viola","zh-cn":"\u4f4e\u97f3\u63d0\u7434"},l={en:"More resources from {1}","zh-cn":"\u66f4\u591a\u8d44\u6e90\u5728 {1}"},
k={en:"Cannot load piece {1} from {2}. Please choose a new one.","zh-cn":"\u65e0\u6cd5\u4ece{2}\u4e0b\u8f7d\u66f2\u76ee{1}\u3002\u8bf7\u9009\u62e9\u65b0\u66f2\u76ee\u3002"},m={en:"Share <b>{1}</b> to your friends using buttons above or your browser's sharing functions!","zh-cn":"\u4f7f\u7528\u4e0a\u9762\u7684\u6309\u94ae\u6216\u8005\u6d4f\u89c8\u5668\u7684\u5206\u4eab\u529f\u80fd\u628a{1}\u5206\u4eab\u7ed9\u4f60\u7684\u670b\u53cb\uff01"};d();return{checkLanguage:d,getProjectName:function(b){return c(a,
b)},getApplicationTitle:function(a){return c(h,a)},getPrintFooter:function(a){return c(l,a,window.location.hostname)},getTranslation:c,getPieceLoadingFailureNotice:function(a,b){return c(k,b,a,App.getPiecesPath())},getSharingTitle:function(a,b){return c(m,b,f(a))},getPieceDescription:f}}();
function MusicPlayer(d){function c(a){for(var e=a.first,c=[],d=0;d<a.verticals.length;d++){for(var f=[],g=0;g<a.verticals[d].notes.length;g++)f.push({color:"black",size:"1.0"});c.push(f)}return{isOnBar:function(a){return e===a.first},changeNotesSize:function(a,b,e){for(var d=0;d<b.length;d++)c[a][b[d]].size=e},changeNotesColor:function(a,b,e){for(var d=0;d<b.length;d++)c[a][b[d]].color=e},drawAllOrnaments:function(){for(var a=0<=navigator.userAgent.toLowerCase().indexOf("firefox"),e=0;e<c.length;e++)for(var d=
0;d<c[e].length;d++){if("1.0"!==c[e][d].size&&!a){var f=b(e,[d]);f[0].style.transformOrigin="50% 50%";f[0].style.transform="scale("+c[e][d].size+")"}"black"!==c[e][d].color&&(f=b(e,[d]),f[0].setAttribute("fill",c[e][d].color))}}}}function f(){a.innerHTML="";var b=new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.SVG);context=b.getContext();b.resize(a.clientWidth,a.clientHeight);context.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return context}function b(a,b){for(var e=document.querySelectorAll("#vf-"+
l[a].attrs.id+" g.vf-notehead path"),c=[],d=0;d<b.length;d++)c.push(e[b[d]]);return c}function e(a){var b=h.getBar(a);return a-b.first}var a=d,h=null,l=[],k=0,m=null;return{setPiece:function(a){h=a;k=0},setFocus:function(a){k=a},display:function(){var a=f(),b=new Vex.Flow.Stave(4,64,a.width-8),e=h.getBar(k);b.addClef(e.clef).addTimeSignature(e.time).addKeySignature(VFUtility.toVFKeySignature(e.key));b.setMeasure(h.getData().bars.indexOf(e)+1);b.setContext(a).draw();l=[];for(var d={},z=0;z<e.verticals.length;z++)l.push(VFUtility.prepareStaveNote(e.key,
e.clef,e.verticals[z],d));d=Vex.Flow.Beam.generateBeams(l);Vex.Flow.Formatter.FormatAndDraw(a,b,l);d.forEach(function(b){b.setContext(a).draw()});null!==m&&m.isOnBar(e)?m.drawAllOrnaments():m=new c(e)},changeNotesSize:function(a,c,d){d=void 0===d?"1.0":d;if(!(0<=navigator.userAgent.toLowerCase().indexOf("firefox"))){a=e(a);for(var f=b(a,c),g=0;g<f.length;g++)f[g].style.transformOrigin="50% 50%",f[g].style.transform="scale("+d+")";m.changeNotesSize(a,c,d)}},changeNotesColor:function(a,c,d){d=void 0===
d?"black":d;a=e(a);for(var f=b(a,c),g=0;g<f.length;g++)f[g].setAttribute("fill",d);m.changeNotesColor(a,c,d)}}}var MusicStorageManager=function(){return{getPiece:function(d){d=localStorage.getItem("_piece_"+d);return null===d?null:Piece.createFromString(d)},setPiece:function(d){d=d.getData();localStorage.setItem("_piece_"+d.id,JSON.stringify(d))}}}();
function MusicViewer(d){function c(){e.innerHTML="";var a=Vex.Flow.Renderer.Backends.SVG;"CANVAS"===e.tagName.toUpperCase()&&(a=Vex.Flow.Renderer.Backends.CANVAS);a=new Vex.Flow.Renderer(e,a);k=a.getContext();a.resize(e.clientWidth,e.clientHeight);k.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return k}function f(b,c,d){c=void 0===c?0:c;d=void 0===d?0:d;var f={"C\u266f":7,"b\u266d":5,"E\u266d":3,"c\u266f":4,d:1,c:3,"a\u266f":7,F:1,B:5,D:2,"G\u266d":6,"B\u266d":2,"g\u266f":5,e:1,"C\u266d":7,
"F\u266f":6,b:2,G:1,"a\u266d":7,E:4,a:0,C:0,"A\u266d":4,"f\u266f":3,"d\u266f":6,g:2,A:3,f:4,"D\u266d":5,"e\u266d":6};c=(0===c?e.clientWidth:c)-8;var g=0===d?e.clientHeight:d;d=Math.floor(g/160);for(var g=40+.33*(g-160*d),h=a.getData(),k=[],n=0;n<d;n++)k.push({height:160,staves:[]});for(n=0;n<d&&b<h.bars.length;n++){for(var m=[],p="",u="",x="",q=b;q<h.bars.length;q++){var v=h.bars[q],r={clef:"",key:"",time:"",verticals:v.verticals.length,size:0};v.clef!==p&&(p=r.clef=v.clef,r.size+=25);v.key!==u&&
(u=r.key=v.key,r.size+=8*f[v.key]);v.time!==x&&(x=r.time=v.time,r.size+=14);r.size+=50*r.verticals;m.push(r)}u=0;p=h.bars.length-b;for(q=b;q<h.bars.length;q++)if(u+=m[q-b].size,u>c){p=q>b?q-b:1;break}for(q=u=0;q<p;q++)u+=m[q].size;for(q=x=0;q<p;q++)l=v=q+b,r=m[q].size/u*c,k[n].staves.push({barIndex:v,left:x+4,width:r}),x+=r;b+=p}return{rows:k,staveOffsetTop:g}}function b(b){var e=a.getData();b=0==b?e.bars.length-1:b-1;for(var c=0,d=0;d<e.bars.length;d++){for(var g=c,h=f(c),k=0;k<h.rows.length;k++)for(var l=
0;l<h.rows[k].length;l++){if(b===h.rows[k][l].barIndex)return 0==k+l?g:c;c=h.rows[k][l].barIndex}c+=1}}var e=d,a=null,h=0,l=0,k=null,m=null;c();return{setPiece:function(b){a=b},setFirstBar:function(a){h=a},display:function(){c();var b=a.getData(),e=f(h),d=e.staveOffsetTop;m=e;for(var l=0;l<e.rows.length;l++){for(var z="",B="",C="",w=0;w<e.rows[l].staves.length;w++){var t=b.bars[e.rows[l].staves[w].barIndex],A=new Vex.Flow.Stave(e.rows[l].staves[w].left,d,e.rows[l].staves[w].width);0==w&&A.setMeasure(e.rows[l].staves[w].barIndex+
1);t.clef!==z&&(z=t.clef,A.addClef(t.clef));t.key!==B&&(B=t.key,A.addKeySignature(VFUtility.toVFKeySignature(t.key)));t.time!==C&&(C=t.time,A.addTimeSignature(t.time));A.setContext(k).draw();for(var u=[],x={},q=0;q<t.verticals.length;q++)u.push(VFUtility.prepareStaveNote(t.key,t.clef,t.verticals[q],x));t=Vex.Flow.Beam.generateBeams(u);Vex.Flow.Formatter.FormatAndDraw(k,A,u);t.forEach(function(a){a.setContext(k).draw()})}d+=e.rows[l].height}},getLastBar:function(){return l},getCurrentLayout:function(){return m},
getFirstBarInPreviousPage:b,getFirstBarInLastPage:function(){return b(0)}}}
var Note=function(){function d(b){var a={A:[0,1],"B\ud834\udd2b":[0,1],"G\ud834\udd2a":[0,1],"A\u266f":[0,2],"B\u266d":[0,2],B:[0,3],"A\ud834\udd2a":[0,3],"C\u266d":[1,3],C:[1,4],"D\ud834\udd2b":[1,4],"B\u266f":[0,4],"C\u266f":[1,5],"D\u266d":[1,5],D:[1,6],"E\ud834\udd2b":[1,6],"C\ud834\udd2a":[1,6],"D\u266f":[1,7],"E\u266d":[1,7],"F\ud834\udd2b":[1,7],E:[1,8],"F\u266d":[1,8],"D\ud834\udd2a":[1,8],F:[1,9],"G\ud834\udd2b":[1,9],"E\u266f":[1,9],"F\u266f":[1,10],"G\u266d":[1,10],G:[1,11],"A\ud834\udd2b":[1,
11],"F\ud834\udd2a":[1,11],"G\u266f":[1,12],"A\u266d":[1,12]};b=c(b);var e=b.natural+b.accidental;return a.hasOwnProperty(e)?(a=a[e],a[1]+12*(b.octave-a[0])):-1}function c(b){var a={natural:"",octave:-1,accidental:""};if(0>=b.length)return a;a.natural=b[0];a.octave=parseInt(b.substring(b.length-1,b.length));a.accidental="";a.accidentalASCII="";2<b.length&&(1==b.indexOf("\u266d")?(a.accidental="\u266d",a.accidentalASCII="b"):1==b.indexOf("\u266f")?(a.accidental="\u266f",a.accidentalASCII="#"):1==b.indexOf("\ud834\udd2b")?
(a.accidental="\ud834\udd2b",a.accidentalASCII="bb"):1==b.indexOf("\ud834\udd2a")&&(a.accidental="\ud834\udd2a",a.accidentalASCII="##"));return a}function f(e,a){var c=b[e],d="";"\u266d"==c.sharpflat&&"BEADGCF".indexOf(a)<c.amount?d="\u266d":"\u266f"==c.sharpflat&&"FCGDAEB".indexOf(a)<c.amount&&(d="\u266f");return d}var b={"D\u266d":{index:0,sharpflat:"\u266d",amount:5},"G\u266f":{index:1,sharpflat:"\u266f",amount:8},"b\u266d":{index:2,sharpflat:"\u266d",amount:5},"C\u266d":{index:3,sharpflat:"\u266d",
amount:7},e:{index:4,sharpflat:"\u266f",amount:1},"C\u266f":{index:5,sharpflat:"\u266f",amount:7},B:{index:6,sharpflat:"\u266f",amount:5},g:{index:7,sharpflat:"\u266d",amount:2},f:{index:8,sharpflat:"\u266d",amount:4},"F\u266d":{index:9,sharpflat:"\u266d",amount:8},a:{index:10,sharpflat:"\u266f",amount:0},G:{index:11,sharpflat:"\u266f",amount:1},"B\u266d":{index:12,sharpflat:"\u266d",amount:2},"e\u266f":{index:13,sharpflat:"\u266f",amount:8},"a\u266f":{index:14,sharpflat:"\u266f",amount:7},"d\u266d":{index:15,
sharpflat:"\u266d",amount:8},d:{index:16,sharpflat:"\u266d",amount:1},"F\u266f":{index:17,sharpflat:"\u266f",amount:6},"g\u266f":{index:18,sharpflat:"\u266f",amount:5},C:{index:19,sharpflat:"\u266f",amount:0},D:{index:20,sharpflat:"\u266f",amount:2},"A\u266d":{index:21,sharpflat:"\u266d",amount:4},A:{index:22,sharpflat:"\u266f",amount:3},"E\u266d":{index:23,sharpflat:"\u266d",amount:3},"f\u266f":{index:24,sharpflat:"\u266f",amount:3},c:{index:25,sharpflat:"\u266d",amount:3},b:{index:26,sharpflat:"\u266f",
amount:2},F:{index:27,sharpflat:"\u266d",amount:1},E:{index:28,sharpflat:"\u266f",amount:4},"G\u266d":{index:29,sharpflat:"\u266d",amount:6},"c\u266f":{index:30,sharpflat:"\u266f",amount:4},"e\u266d":{index:31,sharpflat:"\u266d",amount:6},"a\u266d":{index:32,sharpflat:"\u266d",amount:7},"d\u266f":{index:33,sharpflat:"\u266f",amount:6}};return{flat:"\u266d",sharp:"\u266f",flatflat:"\ud834\udd2b",sharpsharp:"\ud834\udd2a",getNoteOrder:d,getNoteFrequency:function(b){b=d(b);"DoubleBass"===Locale.getApplicationTitle("en")&&
(b-=12);return 0>b?0:440*Math.pow(Math.pow(2,1/12),b-49)},getNoteDetail:c,getDefaultAccidental:f,getDefaultAccidentalASCII:function(b,a){return f(b,a).replace("\u266f","#").replace("\u266d","b")},getFirstNoteInKey:function(b){b=b.substring(0,1);return 0<="GAB".indexOf(b)?b+"3":b+"4"}}}(),PDFConverter=function(d,c){function f(){var c=b.querySelectorAll("div.page");h+=1;h>=c.length?e(a):(a.addPage(),a.addHTML(c[h],f))}var b=d,e=c,a=null,h=0;return{convert:function(){var c=b.querySelectorAll("div.page");
0>=c.length?e(null):(a=new jsPDF("p","pt","a4"),h=0,a.addHTML(c[0],f))}}},PDFPage=function(){function d(){LoadingIconManager.show();var c=document.querySelector("body > div#pdfRenderer");c.style.display="block";var b=new PDFRenderer(c),e=MusicStorageManager.getPiece(App.getDefaultPieceId());null===e?alert("Cannot show PDF"):(b.render(e),(new PDFConverter(c,function(a){c.style.display="none";window.top.pdfdata=a.output("arraybuffer");document.querySelector("body > div#container > div#wrapper").innerHTML=
'<embed src="/pdf.js/viewer.html">'})).convert(e))}var c=function(){return{onComplete:function(){LoadingIconManager.hide()},onerror:onerror}}();return{initialize:function(f){window.top.PDFJS=c;LoadingIconManager.show();document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){window.location=App.getPiecePath()});d();f=App.getPiecePath();history.replaceState("","",f)},draw:function(){},getPath:function(){return"pdf.html"}}}(),PDFRenderer=function(d){return{render:function(c){d.innerHTML=
"";for(var f=-1,b=-1,e=0;8>e;e++){b+=1;f+=1;if(f>=c.getData().bars.length)break;var a;a=b;var h=document.createElement("div");h.classList.add("page");h.innerHTML='<div class="header"></div><div class="title XXX"></div><canvas class="music"></canvas><div class="footer"></div>'.replace("XXX",0===a?"":"hide");d.appendChild(h);a=h;a.querySelector("div.title").innerHTML=Locale.getTranslation(c.getData().descriptions);a.querySelector("div.footer").innerHTML=Locale.getPrintFooter();a=new MusicViewer(a.querySelector("canvas.music"));
a.setPiece(c);a.setFirstBar(f);a.display();f=a.getLastBar()}}}},Piece=function(){function d(c){function d(c){for(var a=0;a<b.bars.length;a++)if(b.bars[a].first<=c&&c<b.bars[a].first+b.bars[a].verticals.length)return b.bars[a];return null}var b=JSON.parse(c);return{getData:function(){return b},getBar:d,getPreBar:function(b){b=d(b);return null===b?null:d(b.first-1)},getNextBar:function(b){b=d(b);return null===b?null:d(b.first+b.verticals.length)},getTotalVerticals:function(){var c=b.bars[b.bars.length-
1];return c.first+c.verticals.length}}}return{createFromString:function(c){return new d(c)}}}(),SharePage=function(){function d(b){var d=b.target.id;d in f?(b=f[d].replace("URL",encodeURIComponent(c.url)).replace("DESCRIPTION",encodeURIComponent(c.description)).replace("VIA","Metronome"),window.open(b,"_blank")):"mail"==d?(b="mailto:?subject="+encodeURIComponent(c.description)+"&body="+encodeURIComponent(c.url),window.open(b,"_blank")):"link"==b.target.id&&(b=document.querySelector("body > input#copy"),
b.classList.remove("hidden"),b.value=c.url,b.select(),document.execCommand("copy"),b.classList.add("hidden"));window.location=App.getPiecePath()}var c={url:"",description:""},f={qq:"http://v.t.qq.com/share/share.php?url=URL&title=DESCRIPTION",weibo:"http://service.weibo.com/share/share.php?url=URL&title=DESCRIPTION",qzone:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=URL&title=DESCRIPTION",facebook:"https://www.facebook.com/sharer/sharer.php?u=URL&t=DESCRIPTION",twitter:"https://twitter.com/intent/tweet?text=DESCRIPTION&url=URL&via=VIA"};
return{initialize:function(b){b=App.getDefaultPieceId();var e=MusicStorageManager.getPiece(b);document.querySelector("body > div#container > div#share > div#title").innerHTML=Locale.getSharingTitle(e);e=App.getHost()+App.getPiecePath();history.replaceState("","",e);c.url=e;e=MusicStorageManager.getPiece(b);c.description=Locale.getPieceDescription(e)+", "+Locale.getApplicationTitle()+", "+Locale.getProjectName();b=document.querySelectorAll("body > div#container > div#share > div#services > div.service");
for(e=0;e<b.length;e++)b[e].addEventListener("click",d);document.querySelector("body > div#container > div#controls > div#ok").addEventListener("click",function(){window.location=App.getPiecePath()})},draw:function(){},getPath:function(){return"share.html"}}}(),StringInstrumentSimulator=function(){function d(){if(null!=c)return!0;if("AudioContext"in window)c=new AudioContext;else if("webkitAudioContext"in window)c=new webkitAudioContext;else return c=null,!1;f=c.createGain();f.gain.value=0;f.connect(c.destination);
return!0}var c=null,f=null,b=[];return{play:function(e){d();for(var a=0;a<e.length;a++)if(!(0>=e[a])){var h=c.createOscillator();h.frequency.value=e[a];var l=h,k=Math.PI,m=new Float32Array(12),g=new Float32Array(12),n=[.49,.995,.94,.425,.48,0,.365,.04,.085,0,.09,0],k=[0,0,k/2,0,k/2,0,k/2,0,k/2,0,k/2,0];m[0]=0;g[0]=0;for(var p=1;12>p;p++)m[p]=n[p]*n[0]*Math.cos(k[p]),g[p]=n[p]*n[0]*Math.sin(k[p]);m=c.createPeriodicWave(g,m);l.setPeriodicWave(m);h.connect(f);h.start(0);b.push(h)}f.gain.linearRampToValueAtTime(0,
c.currentTime);f.gain.linearRampToValueAtTime(.5,c.currentTime+.05)},stop:function(){d();f.gain.linearRampToValueAtTime(.5,c.currentTime);f.gain.linearRampToValueAtTime(0,c.currentTime+.05);setTimeout(function(){for(var c=0;c<b.length;c++){var a=b[c];a.stop(0);a.disconnect(f)}b=[]},50)},playAndStop:function(b,a,c){}}}(),VFUtility=function(){function d(c){c=Note.getNoteDetail(c);return c.natural+c.accidentalASCII+"/"+c.octave}return{toVFKeySignature:function(c){c!==c.toUpperCase()&&(c=c.toUpperCase()+
"m");return c=c.replace(Note.flat,"b").replace(Note.sharp,"#")},prepareStaveNote:function(c,f,b,e){for(var a,h,l,k=[],m=0;m<b.notes.length;m++)k.push(d(b.notes[m]));f=new Vex.Flow.StaveNote({clef:f,keys:k,duration:b.duration});if("r"!==b.duration.substr(-1))for(m=0;m<b.notes.length;m++)a:{var g=c,k=f,n=m,p=e;l=k.keys[n];var y=l.indexOf("/");a=l.substring(0,1);h=parseInt(l.substring(y+1));l=l.substring(1,y);y=a+h;h=!1;if(p.hasOwnProperty(y))if(p[y]==l)break a;else h=!0;p[y]=l;"bb"==l?k.addAccidental(n,
new Vex.Flow.Accidental("bb")):"##"==l?k.addAccidental(n,new Vex.Flow.Accidental("##")):(a=Note.getDefaultAccidentalASCII(g,a),"#"==a?"#"==l?h&&k.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==l?k.addAccidental(n,new Vex.Flow.Accidental("b")):k.addAccidental(n,new Vex.Flow.Accidental("n")):"b"==a?"#"==l?k.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==l?h&&k.addAccidental(n,new Vex.Flow.Accidental("b")):k.addAccidental(n,new Vex.Flow.Accidental("n")):"#"==l?k.addAccidental(n,new Vex.Flow.Accidental("#")):
"b"==l?k.addAccidental(n,new Vex.Flow.Accidental("b")):h&&k.addAccidental(n,new Vex.Flow.Accidental("n")))}c=b.duration;"dd"==c.substring(c.length-2)?f.addDotToAll().addDotToAll():(b=b.duration,"d"==b.substring(b.length-1)&&f.addDotToAll());return f}}}(),App=function(){function d(){f.draw()}var c={},f=null;return{initialize:function(b){b=void 0===b?{}:b;Header.initialize();for(var e=window.location.pathname,a=window.location.search,a=("?"===a[0]?a.substr(1):a).split("&"),h=0;h<a.length;h++){var l=
a[h].split("=");b[decodeURIComponent(l[0])]=decodeURIComponent(l[1]||"")}b.lastPage=sessionStorage.lastPage||null;c=b;f=0===e.indexOf("/db/"+CatalogPage.getPath())?CatalogPage:0===e.indexOf("/db/"+AboutPage.getPath())?AboutPage:0===e.indexOf("/db/"+PDFPage.getPath())?PDFPage:0===e.indexOf("/db/"+SharePage.getPath())?SharePage:IndexPage;Header.highlight(f);f.initialize(b);sessionStorage.setItem("lastPage","/db/"+f.getPath());window.addEventListener("resize",d)},getParams:function(){return c},resize:d,
getHost:function(){var b=window.location.href;return b.substring(0,b.indexOf("/",8))},getPagePath:function(b){return"/db/"+(void 0===b?null:b).getPath()},getPiecePath:function(b){b=void 0===b?null:b;b=null===b?App.getDefaultPieceId():b.getData().id;return App.getPagePath(IndexPage)+"?p="+b},getPiecesPath:function(){return"/db/pieces/"},getDefaultPieceId:function(){var b=c,d="default";b.hasOwnProperty("p")?d=b.p:"lastPieceId"in sessionStorage&&(d=sessionStorage.lastPieceId);return d}}}();
